### ISSUE TITLE
Possibly stuck on Issue syncing

### ISSUE THREAD

**Issue by simonwex** [codetree/feedback#1]
I just imported an admittedly-huge number of repos (All of Mozilla Foundation's) and it's stuck on this screen:

![screenshot 2014-10-31 11 26 48](https://cloud.githubusercontent.com/assets/25260/4866434/e282d872-612b-11e4-9249-fe797acd7aa2.png)

Project id "KqyK"

It's been running for 10 minutes. I could see this being expected behaviour. If that's the case, resolution of this issue would be a more granular status update on-page.

**Comment by derrickreimer** [comment]
Thanks Simon. I'm keeping an eye on the progress on the backend -- it's indeed the largest project imported to date.

Question -- perhaps these repos belong in a number of smaller projects? Or do you prioritize issues on global foundation-wide basis?

> If that's the case, resolution of this issue would be a more granular status update on-page.

I like that approach.

**Comment by derrickreimer** [comment]
Looks like performance is fairly degraded at that scale as well. Optimizations forthcoming.

**Comment by simonwex** [comment]
It loaded, created #2 to track granular status.

**Comment by simonwex** [comment]
I'd say managing user expectations is more important than making it fast.
