### ISSUE TITLE
Answer the "where should I file this issue?" question

### ISSUE THREAD

**Issue by derrickreimer** [codetree/feedback#10]
Requested by @simonwex.

Right now, users given too many decisions to make when filing an issue. (Actually, we need to hide a bunch of options in the new issue modal for users who do not have privileged access to the repository, since GH will ignore these when not allowed).
- Need a clear convention for triaging issues
- Possibly a "move" operation (i.e. closing the original issue, opening a new issue in the desired repo, and dropping a reference back to the original)

**Comment by davidascher** [comment]
For inspiration, this is what our bugzilla does: https://bugzilla.mozilla.org/enter_bug.cgi

(the checkbox autocomplete is the key bit)

it uses data including the descriptions in https://bugzilla.mozilla.org/describecomponents.cgi?product=Air%20Mozilla&component=Community#Community

**Comment by derrickreimer** [comment]
Needs #15 and needs #16.
