### ISSUE TITLE
analytics? burndown charts? cycle times?

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#102]
although I don't feel strongly on this yet (and i'm curious what others think) it seems useful to have:
- cycle time for each ticket (time between work on it starting and finishing, time spent in each lane), which were the fast, which were the slow tickets
- burndown charts

**Comment by ClementChapalain** [comment]
Burndown charts would be super useful. Also a velocity history (for each past sprint) would be great !

**Comment by derrickreimer** [comment]
Noted @ClementChapalain!

**Comment by tnoetzel** [comment]
+1

**Comment by ac21** [comment]
Burndown charts implemented in 2017;  closing ticket
