### ISSUE TITLE
issue incorrectly showing up under "unanswered"

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#103]
I have an issue showing up under "unanswered by `dieterbe`" even though no-one highlighted me after I last commented.

https://github.com/raintank/grafana/issues/91

**Comment by derrickreimer** [comment]
Along with #99, this should be fixed as well.

**Comment by Dieterbe** [comment]
confirmed :)

**Comment by Dieterbe** [comment]
this is happening again.
this time https://github.com/raintank/grafana/issues/327 shows up in my answered despite me being the last person to comment

**Comment by derrickreimer** [comment]
Hmmm. I just looked in the database and I'm showing that a comment came in with GH ID #125363185 at 2015-07-27 22:15:39 UTC from @mattttt that mentioned you, but there appears to be no trace of it now. I'm thinking it must have been deleted. Can you check to see if you got a GitHub notification email for that missing comment?

**Comment by Dieterbe** [comment]
oh i think @mattttt deleted that comment afterwards. there was a notification indeed

**Comment by derrickreimer** [comment]
Ok, I'm going to close this one for now since it's a super edge case. Cases like this will be handled by whatever mechanism we come up with for "marking as answered".
