### ISSUE TITLE
adding linked repositories is clunky

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#105]
my org on GH has 25 repositories.
I think for our initial (and perhaps final) approach I think it makes most sense to just put all our repos into 1 board (maybe with the exception of 1 or 2 repos). We're only a small team of 8-ish working on a variety of issues that span many different repo's but ultimately all serve the same product and goal. (if anyone can comment and why this approach wouldn't make sense, please let me know).

anyway, the processes of linking a whole bunch of repos to the board is clunky:
1. it's a 1 by 1 process.
2. already linked still shows up in the selection interface.  this makes it hard to know which repos I still need to add.
3. it shows repos for my other orgs as well. i have many unrelated repos in other orgs and under my own name, so my select tag list is pretty huge, mostly filled with irrelevant repos. finding the ones to enable is time consuming

longer term, perhaps a list of repositories with a filter and select boxes to enable/disable linking could be nicer as opposed to the current select list to manage the other list.

for the short term, just fixing the 2nd issue in the current mechanism would be pretty useful.
the first issue could also be solved by allowing selecting multiple values in the select list, so i could just use shift-click to select the entire range of projects that start with my org, i.e. `raintank/`

**Comment by ac21** [comment]
closing as this is partially solved in onboarding and limited interest afterwards
