### ISSUE TITLE
Recognize full GH urls when parsing out relationships

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#106]
I have a ticket that depends on a ticket in another repo.
my workflow is as follows:
- add comment stating `needs https://github.com/raintank/ops/issues/40`
- note i just copy-pasted in the url, which is super easy because:
- github auto turns this into a link so that the message is `needs raintank/ops#40` (the latter being link)

unfortunately codetree doesn't seem to recognize the needs relationship, also after github sync data.

**Comment by derrickreimer** [comment]
Interesting, I was not aware that GitHub auto converts full URLs to the `user/repo#xxx` format and recognizes it as a reference. I can add support for this in Codetree soon.

For now, you need to reference it like this for cross repo dependencies to be picked up by CT: `needs raintank/ops#40`.

**Comment by derrickreimer** [comment]
This one should be fixed :+1:
