### ISSUE TITLE
Request: "Create Another" button

### ISSUE THREAD

**Issue by moodonis** [codetree/feedback#108]
When filing many issues, it would be helpful to have a "Create Another" button that creates the issue that you're working on, but pops up another modal window with a blank title and body. 

Repo information, assignee, priority and milestone can be inherited.

**Comment by derrickreimer** [comment]
Hi @moodonis! This should actually be the default behavior right now - the modal is supposed to clear but stay open after creating an issue in Codetree. Is this not happening for you? If not, could you tell me which browser + OS you are using?

**Comment by moodonis** [comment]
@djreimer this actually does work as intended. It's just not obvious it does that until you actually create an issue. I'm using Safari latest on OSX 10.10.3
