### ISSUE TITLE
tickets jump back when trying to move into a lane

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#110]
in the kanban board, when i try to move a ticket from backlog to to-do, it keeps jumping back :?

**Comment by derrickreimer** [comment]
The reason for this is that is an ambiguous operation. Issues belong in the To Do column once they have a milestone, but when dragging into the To Do column when the board is not filtered down to one milestone we are unable to infer which milestone to apply to the issue.

The solution for now: filter by the milestone you'd like the issue to fall under first, then drag from Backlog into To Do and we will apply the milestone.

I have a feature in my pipeline to add a prompt for more info when an ambiguous op is performed, along the lines of "Which milestone would you like to apply to this issue?"

**Comment by Dieterbe** [comment]
that would be great
