### ISSUE TITLE
Add assignee to custom stage

### ISSUE THREAD

**Issue by jamesraby** [codetree/feedback#114]
Would love to have ability to have stages for assignees vs just labels.

This way - we can balance issues easily amongst the team.

Great product by the way.

**Comment by kareem** [comment]
@jamesraby Interesting.  Are you asking for a feature that would let you move to a stage when an issue is assigned to a person?  Or when an issue is moved to a stage to auto-assign it to a person?

Related - we are working on a feature that I think will help with this.  Can we run some mocks by you and get your feedback?  If so please drop ryan@codetree.com a line - he's driving the feature over here.

**Comment by ac21** [comment]
replaced by #354
