### ISSUE TITLE
Setup issue dependencies using "blocks ####" as well as "needs ####"

### ISSUE THREAD

**Issue by rsyring** [codetree/feedback#117]
Basically, just allow both setups of terminology.  I've used "blocks" terminology in lots of other project management systems and it seems more intuitive to "needs" IMO.  

If you accept #116, then you'd also want to support "blocked-by ####".

**Comment by rsyring** [comment]
> We accept "need", "needs", "needed", "require", "requires", "required" (similar to GitHub's "fixes" convention for pull requests).

Just documenting this since I found it in another issue.  Are there docs for codetree anywhere?

**Comment by derrickreimer** [comment]
We have some official docs in the works, but not live at this point.
