### ISSUE TITLE
Issues and milestones should be top level in side bar

### ISSUE THREAD

**Issue by robchandhok** [codetree/feedback#122]
There's an inconsistency in the wasy you move from Issues to Milestones.  I think it's too hard to flip, and would appreciate "milestones" and "issues" always being the top level rather than a pull down.  Also in the milestones view the option "milestones _is_ in the sidebar.  

anyway needs a tiny bit of dusting.

**Comment by derrickreimer** [comment]
Yes I'd have to agree that a little reorganization is in order. The milestones (and labels) pages have become more feature-rich over time and deserve better placement.

**Comment by derrickreimer** [comment]
Shipped! :tada:

**Comment by robchandhok** [comment]
Very cool!

you might want to tweak the pulldown menu, it always says “issues”.  or remove it  and   pye proc settings somewhere else.
