### ISSUE TITLE
When are the dependency keyword tested for?

### ISSUE THREAD

**Issue by mrenvoize** [codetree/feedback#129]
I'm struggling to work out when a dependency keyword (like 'needs') is looked for..
- Is it only in new comments?
- Is it in edited comments?
- Does the milestone status make a difference?
- Does the milestone due date make a difference?

**Comment by derrickreimer** [comment]
Hi Martin, sorry for the confusion. Dependencies will be picked up from the following places:
- In the body of a new issue (immediately)
- New comments (immediately)
- Edited issue body (within one hour)

I'm afraid we don't sweep up dependencies from _edited_ comments. GitHub doesn't send webhooks when comments are edited and it is very expensive (in terms of compute & rate limit) to constantly recheck every comment for changes.

**Comment by derrickreimer** [comment]
Also, milestone status/due date do not factor in to dependency tracking.

**Comment by mrenvoize** [comment]
Cheers for the prompt reply @djreimer , that certainly make it much clearer for me :)

**Comment by derrickreimer** [comment]
:beers:
