### ISSUE TITLE
Ability to sum agile pts for a specific view

### ISSUE THREAD

**Issue by ajwaxman** [codetree/feedback#130]
The ability to add story points to issues (https://github.com/codetree/feedback/issues/18) has been helpful as we try to move our very manual google spreadsheet sprint process into a software solution like Codetree. 

One enhancement to that feature that would be just as helpful for us is the ability to view total pts for the current view. So if the board is organized by Assignee with a specific label filtered you'd be able to see the sum of pts for each user for issues with the filtered label.

Quick mockup of what I had in mind:

![](http://cl.ly/cmUc/Image%202015-08-26%20at%206.33.03%20PM.png)

In addition to pts broken down by Assignee / Milestone, it's be great to have the ability to see the number of pts of all the Assignees / Milestones combined:

![](http://cl.ly/ck7u/Image%202015-08-26%20at%206.31.39%20PM.png)

**Comment by ezra-g** [comment]
I work with @awaxman11 and wanted to reiterate that this capability would be helpful to making the case to use CodeTree more regularly internally.

**Comment by derrickreimer** [comment]
@awaxman11 @ezra-g thanks gents. This is definitely doable. I'll try to get this knocked out soon for you. :+1:

**Comment by ezra-g** [comment]
Wowza - Thanks for the fast response, @djreimer!

**Comment by ajwaxman** [comment]
@djreimer thanks for the quick response!! :smiley:

**Comment by derrickreimer** [comment]
All this is live except the combined total points (still pondering the best way to represent that in the UI). :thought_balloon:

**Comment by ajwaxman** [comment]
Thanks! :clap: :clap:

**Comment by ezra-g** [comment]
Thanks! We'll get to testing soon :).

Ezra Barnett Gildesgame | http://ezra-g.com
