### ISSUE TITLE
Global Shortcuts UI ambiguous 

### ISSUE THREAD

**Issue by nZac** [codetree/feedback#131]
I read through #48 and #66 was closed as a duplicate.

I am looking to create a global shortcut that is shared for the project/projects, is this possible, if so I am not sure how to do it. Thanks for any assistance.

**Comment by derrickreimer** [comment]
Hey @nZac, sorry for the ambiguity - the thread on #48 did steer a bit off topic. We don't have the type of global shortcuts you are talking about, but we should be able to get this added soon. I will keep you in the loop :+1:

**Comment by johanbillgren** [comment]
+1 for this request.

**Comment by derrickreimer** [comment]
Shipped! :shipit: 

![global-shortcuts](https://cloud.githubusercontent.com/assets/341387/10712778/88a79bf2-7a58-11e5-877f-e2129957158d.png)

**Comment by nZac** [comment]
Thanks @djreimer & the team over there!

**Comment by rsyring** [comment]
Thanks for this. :+1:
