### ISSUE TITLE
"needs" links not detected

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#133]
1. in https://github.com/raintank/ops/issues/120 i put `needs #123` as a new comment
2. in https://github.com/raintank/ops/issues/78 and https://github.com/raintank/ops/issues/106 i put `needs #101` as a new comment. one of them also has some other text in the comment. edit: 101 has been closed, so maybe that's why the needs doesn't show, though i think they also didn't show before.
3. in https://github.com/raintank/raintank-metric/issues/11 i put `needs https://github.com/raintank/ops/issues/101` as a single comment.

none of the dependencies are shown in codetree :(

**Comment by Dieterbe** [comment]
hmm now the first one showed up. it took about 15 minutes :(

**Comment by derrickreimer** [comment]
@Dieterbe did they all show up eventually? Looks like our background message queue may have gotten a bit large when the delay happened. I've added additional capacity to mitigate this.

**Comment by Dieterbe** [comment]
i think so.
but now seeing this happen again.
needs relations not being updated in codetree ui :(

update: now they did show up, it just took a while

**Comment by derrickreimer** [comment]
Ah, I believe I was able to reproduce this. I deployed a fix and resynced your project so that those prior references should appear now.
