### ISSUE TITLE
Request - Recent Activity tab

### ISSUE THREAD

**Issue by irvincee** [codetree/feedback#134]
Several of my team members create and close tickets in Codetree. I run into the problem of not knowing who created an issue and where in the taskboard the issue was filed (in progress, code review, etc.). 

I find myself going to Github to identify who created the issue and, subsequently, the task board state (in progress, code review, etc.).

I'd like to request a "Recent Activity" tab feature that displays:
- newly created issues 
- closed issues 

This would be awesome :)

**Comment by derrickreimer** [comment]
I like this :+1:
