### ISSUE TITLE
Ability to filter assignee selection

### ISSUE THREAD

**Issue by pzuraq** [codetree/feedback#135]
When trying to assign a user to an issue, if the relevant orgs are large there can be a huge amount of people to choose from. This means a _lot_ of scrolling. A simple regex filter at the top would really help this.

**Comment by derrickreimer** [comment]
@pzuraq you're in luck! I have a (nearly complete) version of this feature that should deploy in the next few days. I've felt a similar pain.

**Comment by pzuraq** [comment]
:smile:

**Comment by dallasgutauckis** [comment]
> in the next few days

Is this in place somewhere now or is this still pending release?

**Comment by derrickreimer** [comment]
Still pending release - it got rolled into a larger feature that has a few blockers. Will keep this thread informed.

**Comment by derrickreimer** [comment]
Missed updating this issue back when it was released. Shipped!
