### ISSUE TITLE
Assignee selection hidden by element overflow

### ISSUE THREAD

**Issue by pzuraq** [codetree/feedback#136]
![image](https://cloud.githubusercontent.com/assets/685518/9888579/b4c53482-5baa-11e5-9234-8636fbd3a125.png)

**Comment by jacobpierce** [comment]
:+1: 

Does allow scrolling down to view it. It's particularly a problem when there are only 1-3 issues on a column.

![codetree-overflow](https://cloud.githubusercontent.com/assets/597902/10133580/21e43a38-65d6-11e5-8055-ef11a37c9b13.png)

**Comment by derrickreimer** [comment]
This is fixed by our new issue editing inferface :+1:
