### ISSUE TITLE
Issue title disappears after expanding to show pull request

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#138]
Per this animated gif. I'm using the latest version of Google Chrome ( 45.0.2454.101 (64-bit) on Mac OS 10.11 Beta.
![](http://g.recordit.co/Uz5T0Shm5y.gif)

**Comment by derrickreimer** [comment]
I've noticed this one as well...Chrome bug. Will see what I can do to hack around it, seems like we need to force a repaint after toggling.
