### ISSUE TITLE
Repo picker in new issue modal isn't sorted logically

### ISSUE THREAD

**Issue by jbt** [codetree/feedback#144]
It looks like it's sorted in reverse order of when the repos were added to the project. Would be great if it could be alphabetical or something because as soon as there's more than a few repos in there it's absolutely impossible to find anything.

**Comment by derrickreimer** [comment]
:+1: thanks @jbt. I will fix this promptly.

A _major_ overhaul of the new issue form + a shiny new edit form is in progress. Stay tuned for that.

**Comment by jbt** [comment]
:+1: excellent stuff, much nicer now :)
