### ISSUE TITLE
Update issue description from CodeTree

### ISSUE THREAD

**Issue by cdaguerre** [codetree/feedback#145]
First of all, great job!
Only been playing around with Codetree for a couple a minutes and find it amazingly clean, powerful and simple. Been searching for this kind of app for a while.

The only problem for now, is that our product owners don't want to go to Github at all ;) 

It seems there are only few features missing to allow non-github users to efficiently use codetree, ie.:
- view issue comment history from codetree
- post issue comment from codetree
- issue description update from codetree, although this wouldn't even be mandatory if they could at least reply to comments
- maybe non-github user registration (would probably require some sort of CodeTree bot on Github which would handle non-github user actions...)

Are these features in the roadmap in a foreseeable future?
Once again, great job. Keep it up!

**Comment by derrickreimer** [comment]
Most of this is doable now with our issue editing interface :+1:
