### ISSUE TITLE
Ability to preview markdown when creating a new issue

### ISSUE THREAD

**Issue by Too-Funky** [codetree/feedback#148]
After recently migrating to codetree i miss a few of the standard github issues features including ability to preview markdown and also the ability to paste attachments directly into the issue.

**Comment by derrickreimer** [comment]
This is coming soon! A complete overhaul of the issue creation form is under development, as well as an editing interface for issues.

**Comment by Too-Funky** [comment]
Awesome, looking forward to it!

**Comment by jamemackson** [comment]
:+1:

**Comment by derrickreimer** [comment]
Previews for all!

**Comment by arifb** [comment]
Hi all, we recently launched drag/drop file attachments in Codetree. Any feedback, let me know, thanks!
