### ISSUE TITLE
"Application Error" Page

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#149]
I'm getting long page load times or an "Application Error" at https://codetree.com/projects/1iG4/issues?labels=%2Cstatus%3A+in+sprint%2Cteam%3A+1 .

![https___codetree_com_projects_1ig4_issues_labels__2cstatus_3a_in_sprint_2cteam_3a_1](https://cloud.githubusercontent.com/assets/349595/10588357/ac58708c-7673-11e5-8a6c-a81faacd1530.jpg)

**Comment by derrickreimer** [comment]
We are currently investigating an outage with an upstream provider. Updates here: http://status.codetree.com/

**Comment by ezra-g** [comment]
Thanks!
