### ISSUE TITLE
Allow .5 points as a point value

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#150]
I'm working with teams who occasionally have small tasks and would like to be able to have 1/2 a point (.5) as a point value.

**Comment by jamemackson** [comment]
:+1:

**Comment by ezra-g** [comment]
This one sure would be handy. Any rough sense of if/when this might be available?

**Comment by derrickreimer** [comment]
Sorry for the long wait. Let me try to expedite this one.

On Thu, Dec 3, 2015 at 12:10 PM, Ezra Gildesgame notifications@github.com
wrote:

> This one sure would be handy. Any rough sense of if/when this might be
> available?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codetree/feedback/issues/150#issuecomment-161769131.

## 

Derrick

**Comment by derrickreimer** [comment]
Shipped!

**Comment by ezra-g** [comment]
@djreimer Great - Thanks!

**Comment by ajwaxman** [comment]
Just realized this was live! :smiley: :clap: :clap: :clap:
