### ISSUE TITLE
Ability to create team-wide shortcuts

### ISSUE THREAD

**Issue by adambair** [codetree/feedback#153]
Currently if you create a shortcut it's only visible to you -- it would be super helpful to be able to create shortcuts (as a pm/team lead) to create shortcuts for everyone else on the team so we can be on the same... page ;)

**Comment by adambair** [comment]
Having this could be a workaround for #152 -- just have all teams (ios, android, web) in the master project -- with team-wide shortcuts scoped to different repositories.

**Comment by derrickreimer** [comment]
Sorry for the delay!

Yes, I think this is the right solution for #152, as sort ordering is tightly linked to projects. This is also being tracked on #48.

**Comment by derrickreimer** [comment]
I will try to expedite global shortcuts - this feature request has been hanging around in the queue for far too long. :+1:

**Comment by adambair** [comment]
Awesome -- that would work well for us (and probably others) with the same issue. Much appreciated!

**Comment by adambair** [comment]
And it's likely MUCH easier implementation. Honestly, the other ticket was a swing for the fences / maybe it's in the works type of thing :)

Cheers, thanks!

**Comment by derrickreimer** [comment]
Shipped! :shipit: 

![global-shortcuts](https://cloud.githubusercontent.com/assets/341387/10712780/98c77566-7a58-11e5-8108-cfe8d1775824.png)

**Comment by adambair** [comment]
Yes! Thank you -- this is great!
