### ISSUE TITLE
Change "closed" icon/color

### ISSUE THREAD

**Issue by adambair** [codetree/feedback#154]
Red feels like something is wrong or needs attention -- http://cl.ly/image/2u2G0p370G3D

Perhaps a simple checkmark that's the same brown as the text in the milestone header?

**Comment by derrickreimer** [comment]
Hmm...I'll have to think hard about this one. The red color+icon is a GitHub convention. To deviate from that visual language may cause cognitive "friction".

![image](https://cloud.githubusercontent.com/assets/341387/10699332/c6e11752-796a-11e5-8c87-afcc890dad35.png)

**Comment by adambair** [comment]
Huh, hadn't noticed -- if that's convention no need to rock the boat; it just stuck out for me this context for some reason.

**Comment by adambair** [comment]
Yeah, feel free to ditch this one as well :)

**Comment by derrickreimer** [comment]
Closing this for now. I do appreciate your participation here, though!
