### ISSUE TITLE
Use autocomplete when changing a milestone, not radios

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#157]
We have a long list of milestones (eg dozens of milestones). It would be great to put an issue in a milestone using an autocomplete UI  rather than reading through all the milestones as a list of radios:

![seatgeek__tixcast___clients_-_issues_ _codetree](https://cloud.githubusercontent.com/assets/349595/10800024/41ff5754-7d86-11e5-9902-f20b6a7eda67.jpg)

**Comment by derrickreimer** [comment]
:+1: for sure. This has already made it's way to the filter bar - will be blanketing all dropdowns with this functionality soon.

![image](https://cloud.githubusercontent.com/assets/341387/10800098/739a84a0-7d6d-11e5-98ef-2e408184f1bd.png)

**Comment by ezra-g** [comment]
Sounds great. Thanks!
