### ISSUE TITLE
Filter "assigned to anybody" doesn't seem to work

### ISSUE THREAD

**Issue by adambair** [codetree/feedback#159]
Click filter, assignee, anybody, apply and nothing happens... -- it still shows unassigned tickets http://cl.ly/image/0H3a152N141u

**Comment by derrickreimer** [comment]
Yeah, the word "anybody" is not entirely clear in this case - it means "anybody or nobody". We actually don't have a filter that only excludes unassigned issues at present time. Are you in need of such a filter?

**Comment by adambair** [comment]
anybody and nobody -- would have expected them to be opposite of each other -- it would be nice to be able have this flag set automatically instead of clicking on everyone in the list to find all assigned issues across the teams.
