### ISSUE TITLE
milestone created on github hasn't synced for 13 minutes

### ISSUE THREAD

**Issue by carlshimer** [codetree/feedback#162]
13 Minutes later I don't see it on codetree.  I probably should have created the milestone on codetree first...

**Comment by carlshimer** [comment]
oh... I didn't see the refresh button.  well, that picked it up.  should it be automatic?

**Comment by derrickreimer** [comment]
@carlshimer unfortunately, GitHub does not send us a webhook when a milestone is created. We poll for those changes hourly, but you can also manually refresh on the milestones page to force a sync sooner.
