### ISSUE TITLE
Consider hiding issue labels that are included in the filter

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#163]
If I'm filtering to show only issues that include a given label, it seems redundant to show that label for each issue.  For example, in this view, it seems worth considering not showing the the `team: 1` and `status: in sprint` labels for each issue to make room for other issue labels

![banners_and_alerts_and_seatgeek__tixcast___clients_-_issues_ _codetree](https://cloud.githubusercontent.com/assets/349595/10889362/a89fbae4-815f-11e5-975e-9a916fd312c4.jpg)

**Comment by derrickreimer** [comment]
Seems reasonable to me. Gmail does this as well.

**Comment by kareem** [comment]
Closing probably won't do this.  I hear why you'd want to do this for the sake of visual noise, but seeing the labels gives the customer confidence that the issues being displayed match the filter.  I'm not sure it's worth the tradeoff.  @ezra-g LMK if you strongly disagree and why.  Thx.
