### ISSUE TITLE
"No assignee" table should appear asynchronously

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#164]
In a list view of issues where all issues are assigned, unassigning the issue causes the issue to disappear form the Codetree view until the page is refreshed, because the "No assignee" table doesn't appear asynchronously. I'd suggest that the table appear without refreshing the page, or that it always appear by default.

**Comment by kareem** [comment]
Totally agreed @ezra-g.  On our list.

**Comment by kareem** [comment]
Related request for milestones: https://github.com/codetree/codetree/issues/520

**Comment by kareem** [comment]
Hey @ezra-g just shipped a fix for this for both assignees and milestones.  Please let me know if you see any problems.

![2017-07-27 at 1 03 pm](https://user-images.githubusercontent.com/26123/28689910-2aa8e77c-72cc-11e7-9edf-e15b36939f52.gif)
