### ISSUE TITLE
Duplicate issues in backlog

### ISSUE THREAD

**Issue by dphaener** [codetree/feedback#165]
See attached, issue #154 is shown twice

<img width="293" alt="screen shot 2015-11-02 at 8 38 50 pm" src="https://cloud.githubusercontent.com/assets/5187971/10901369/d0fcec68-81a1-11e5-9136-2a537b45213a.png">

**Comment by derrickreimer** [comment]
Still showing after page refresh? I think there was probably a slight pagination discrepancy in the infinite scrolling.

**Comment by dphaener** [comment]
Ah. Yeah after refresh it’s gone. Darn infinite scrolling.

**Comment by derrickreimer** [comment]
Technically a bug, but going to close this one. Will probably need to switch to cursor-based pagination to ultimately keep this from happening.
