### ISSUE TITLE
Put currently applied label filters at top of checkbox list

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#167]
Currently when removing an selected label that is being used to filer a list view, I have to scroll all the way through the full list of labels to remove it. It seems like it would be ideal to present the selected labels at the top of the list of checkboxes so that I can more easily uncheck them.

![tixcast___product_-_issues_ _codetree](https://cloud.githubusercontent.com/assets/349595/10954153/c6ccbb8c-8319-11e5-883e-460fe0fa6a97.jpg)

**Comment by derrickreimer** [comment]
:+1:

**Comment by derrickreimer** [comment]
:shipit:
