### ISSUE TITLE
Unable to refresh list of organizations and repositories in project

### ISSUE THREAD

**Issue by simonwex** [codetree/feedback#17]
I've created a new org and repos. I'd like to be able to add them to an existing codetree org. How do I refresh the list?

**Comment by derrickreimer** [comment]
I need to add a UI component for this. Should able to get this shipped today. In the meantime, I just ran the sync manually -- do you see them in your available repos now?

**Comment by derrickreimer** [comment]
This should do it.

![refresh-button](https://cloud.githubusercontent.com/assets/341387/5371164/324564dc-7fe6-11e4-9a73-f3ad6cf0f19e.png)
