### ISSUE TITLE
What do the white/peach rows mean?

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#170]
In the list view of issues, some rows are white colored whereas others are peach colored. They don't seem to be zebra-striped. What does this coloration indicate?

**Comment by derrickreimer** [comment]
White means the issues are explicitly prioritized, while tan means that they are unprioritized. The unprioritized issues appear in chronological order of creation until they are explicitly prioritized, at which point they appear above the unprioritized issues. This is a unique feature of Codetree that helps prevent unintentional "implicit" ordering of issues.

**Comment by ajwaxman** [comment]
One of my favorite features :+1:
