### ISSUE TITLE
Doubts about onboarding

### ISSUE THREAD

**Issue by bedhed** [codetree/feedback#171]
I'm not sure, but at the moment, if I want someone to join codetree (and say 3 projects within), I need to:
- Look for the username on github
- Ctrl-c the username
- Go in the first project
- Ctrl-v the username
- Drag & drop the user to full access
- Go to the second project
- Drag & drop the user to full access
- Go to the third project
- Drag & drop the user to full access

Even if the user already had the github access to the repositories of each project ?

How am I supposed to get my 100+ colleagues on board ?

**Comment by derrickreimer** [comment]
Hmm that is not an ideal experience. We can definitely improve in that area. To make things a little easier, I'd be willing to manually add all your users for you. You can email me a list of usernames or you can add them as members on your Codetree organization and I can take care of granting them access to all your projects.

There is definitely ongoing internal debate about how to improve our permissions over all. For now, we err on the side of caution.

**Comment by bedhed** [comment]
Thanks, that's a nice offer.
(Still hoping there will be some tight intergration with github's teams soon ; as the point of codetree is to bring a **great** UX/UI layer above issues & PR, it sound logical to me to do the same for rights).

On an other subject, where would be the best place to talk about pricing ? I just noticed your max license is for 50 users (and also wondering if we're not too big for codetree and perhaps expecting a different product from what you shoot for).

**Comment by derrickreimer** [comment]
Let's continue the conversation via email :+1:
