### ISSUE TITLE
Allow "Keep label when stage is changed" for "Open" column

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#172]
We're using the label `status: in sprint` for our `Open` column so that our Codetree list view shows a list of issues in the current sprint. Currently, Codetree removes the `status: in sprint` label once issues are closed, which makes it difficult to see which issues have been closed within the current sprint.

It would be ideal to have the "Keep label when stage is changed" option so that we could leave the `status: in sprint` (Open column) label on when issues are closed. under our workflow, we'd probably go and remove that label from closed issues once the sprint is over.

Here's a screenshot showing the end result of what this might look like in the list view: Issues closed within the sprint are easy to see at a glance for all assignees on the team, with greater information density than the board view.

<img width="869" alt="slack-imgs_com" src="https://cloud.githubusercontent.com/assets/349595/11659582/0a2e4516-9d97-11e5-9037-37a8c52ff233.png">

**Comment by kareem** [comment]
Hi @ezra-g if this is still important to you can you help us understand something? 
- Why is `status: in sprint` a stage label?  If it wasn't a stage label I don't think you'd have this problem.
- Why not put the tickets in your sprint in a Milestone?

Thanks.

**Comment by kareem** [comment]
BTW going to close this. If it's still an issue for you please reply and we'll re-open and address it.
