### ISSUE TITLE
Stuck on server error screen

### ISSUE THREAD

**Issue by clarkbk** [codetree/feedback#174]
Been using Codetree for months and never had any problems, but I did something this morning to make it angry and now I cannot escape this error screen:

<img width="815" alt="we_re_sorry__but_something_went_wrong__500_" src="https://cloud.githubusercontent.com/assets/1349496/11787505/035d2fc8-a25a-11e5-93c3-98d0b50cbe2d.png">

Remedies I've tried so far to no avail:
- cache-refreshing my browser
- navigating to https://codetree.com (redirects to the project URL and displays the same error)
- appending arbitrary querystring params to the project URL
- signing out using https://codetree.com/signout and then signing back in again
- signing in in a new browser session/incognito window

Other Codetree users in my office confirm that the site is generally still available/functioning for them, but this particular project/board is not.

**Comment by derrickreimer** [comment]
That's no good! Let me have a look...

**Comment by derrickreimer** [comment]
This should be fixed now - sorry for the trouble. Some fluke must have happened during a GitHub sync operation, which left one issue with half corrupted data.

**Comment by clarkbk** [comment]
thanks @djreimer !
