### ISSUE TITLE
Allow Ctrl+Enter to submit comment form

### ISSUE THREAD

**Issue by jbt** [codetree/feedback#175]
Firstly, got to say I'm really digging the new detail / edit view. Very nice.

One thing I'd love to see is the ability to use <kbd>Ctrl</kbd>+<kbd>Enter</kbd> / <kbd>Cmd</kbd>+<kbd>Enter</kbd>\* to submit the comment form - I'm in the habit of using my keyboard as much as possible and having that would be great, just like GH does it.

\* for all I know you may already have done <kbd>Cmd</kbd>+<kbd>Enter</kbd> for macs, but I don't have mine to hand to check, <kbd>Ctrl</kbd>+<kbd>Enter</kbd> is what I naturally reach for on my not-mac.

Also, I just noticed GH has fancy styling for `<kbd>` elements, which'd also be awesome to have, but that's a separate issue

**Comment by derrickreimer** [comment]
:+1: expect to have this soon! Also, I didn't know `<kbd>` tags were a thing :smile: - will add some styles for that.

**Comment by derrickreimer** [comment]
Should work now :tada:

**Comment by jbt** [comment]
Nice one! :+1:

**Comment by alexykot** [comment]
This works on the comment form, but it does not work on the Create Issue form. Can you as well make it submit new issue by Ctrl+Enter when editing Issue title or text?

Created new issue #311 instead of reviving this old thread.
