### ISSUE TITLE
Unable to add member to organization

### ISSUE THREAD

**Issue by alonnovy** [codetree/feedback#176]
We had a particular user in our organization with Codetree, and all was well.  Today that user no longer appears in our organization and when we try to add him back in, the system tells us "User not found".

**Comment by derrickreimer** [comment]
@alonnovy that's odd - can you provide the username? We can move this to email if you'd rather not disclose in public.

**Comment by alonnovy** [comment]
Hi Derrick - thanks for the prompt response.

I just tried it again now, and suddenly it worked....  Perhaps the usernames are case sensitive and I got the case wrong somewhere?  That might explain why I couldn't add the user, but it wouldn't explain why he went missing.
Anyways, it seems to be all OK now.

Thanks again.
