### ISSUE TITLE
Clicking to edit issue size from a task board view opens the issue modal window

### ISSUE THREAD

**Issue by clarkbk** [codetree/feedback#177]
This makes the size uneditable as far as I can figure.

**Comment by derrickreimer** [comment]
D'oh...on it...

On Monday, January 4, 2016, Ben Clark notifications@github.com wrote:

> This makes the size uneditable as far as I can figure.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codetree/feedback/issues/177.

## 

Derrick

**Comment by derrickreimer** [comment]
Should be fixed now.

**Comment by clarkbk** [comment]
Gracias, señor!
