### ISSUE TITLE
The new issue detail modal feature makes it difficult to edit points

### ISSUE THREAD

**Issue by ajwaxman** [codetree/feedback#178]
While the new modal feature makes a lot of things easier, it makes it a bit difficult to edit points. Every time I try and edit the size of an issue the modal pops up. For now I've been holding down my mouse until I edit the size, but it'd be nice to not have to do that.

**Comment by derrickreimer** [comment]
Sorry @awaxman11 - a fix for this is actually going live as we speak!

**Comment by ajwaxman** [comment]
Perfect, thanks!! You continue to amaze me with these issue response times :)
