### ISSUE TITLE
Labels sorting should be consistent with Github

### ISSUE THREAD

**Issue by mazesoul** [codetree/feedback#179]
Hi, 

first of all, thanks for your product. It's working great for us! 

Now for the bug, when you go to the label edition page, the labels are sorted according to github (ASCII I believe). In the list display or the issue edition popup, the labels are sorted using lowercased, stripped special chars. 

It would be nice if all of codetree would sort labels the same as github.

**Comment by derrickreimer** [comment]
Great to hear Codetree is working well for you! This bug should be fixed now.
