### ISSUE TITLE
Assigning agile points to issues

### ISSUE THREAD

**Issue by derrickreimer** [codetree/feedback#18]
Requested by @awaxman11. Would prefer label-based storage (e.g. "size-1", "size-8").

I'm leaning toward comment/body-based storage, like this: `points:5`. Another option is title-based, like this: `Assigning agile points [5]`, where `[5]` indicates point value.

Notify https://secure.helpscout.net/conversation/64951821/67/

**Comment by ajwaxman** [comment]
@djreimer is this live yet? Looks like it's part of a feb milestone. Wasn't sure if you deployed features as they were finished or waited until all the issues in the milestone were completed first. I'm excited to try it out!

**Comment by derrickreimer** [comment]
@awaxman11 Yeah I soft launched the first iteration of this over the weekend (we continuously deploy). I'll do a bigger announcement once I have a launch blog post / docs to back it up, but you are welcome to try it out. To enable point estimates, head to your project settings and tick the enable box. We opted to store points in the title, in the form of `Issue title here [2]`. This makes it visible when looking at the issues list on GitHub, keeps label noise down, and provides an audit trail on GitHub, since changes to the title show up in the feed.

We'll still be adding more functionality around this, like progress indicators and point totals, but I wanted to get the initial feature rolled out first. Let me know what you think!

**Comment by ajwaxman** [comment]
Awesome, checking it out now!

**Comment by derrickreimer** [comment]
:+1:
