### ISSUE TITLE
need a previous/next button + keyboard shortcut to quickly move through detailed views from search results

### ISSUE THREAD

**Issue by RussTedrake** [codetree/feedback#180]
I consider this a major missing feature from github (i'm not alone: https://github.com/isaacs/github/issues/366 ), and it's one that codetree could presumably implement easily.  Thanks for considering.

**Comment by derrickreimer** [comment]
:+1:

**Comment by kareem** [comment]
Hi @RussTedrake we just launched this.  Type `j` or `k` on an Issue Modal and you'll go to the next / prev issue in the group (if the issue was opened from List view) or in the column (if the issue was opened in Board View).

**Comment by RussTedrake** [comment]
Great.  Thanks!
