### ISSUE TITLE
Renaming a milestone doesn't update milestone name in individual issues 

### ISSUE THREAD

**Issue by seocam** [codetree/feedback#182]
After I renamed a Milestone the issues were grouped in the right way but the milestone name appears wrong inside codetree. For example, I've renamed the milestone alpha to "Iteration #1" and that was the result I got:

<img width="1094" alt="screen shot 2016-02-03 at 12 42 18 pm" src="https://cloud.githubusercontent.com/assets/33388/12785437/ae0a1558-ca73-11e5-9df0-cf02fb3bd468.png">

It's all grouped as Iteration #1 but the issues are showing up as Alpha. I've tried renaming in Github and the effect was the same. I've also tried to resync but didn't work either. On github the milestone info is showing up properly.

**Comment by derrickreimer** [comment]
Sorry for the confusion. Because of the way we cache milestone names, the issues view should be consistent within one hour of renaming a milestone.
