### ISSUE TITLE
Milestones are not created in one of my repositories

### ISSUE THREAD

**Issue by seocam** [codetree/feedback#184]
The milestone is not created in one of my repos and the tasks in that repo doesn't appear on CodeTree.

I'm able to create issues using codetree but the issue does not show up anywhere.

**Comment by derrickreimer** [comment]
Hi @seocam - can share the repo name that's giving you trouble? You can email me (support at codetree) as well if you'd prefer to keep this private.

**Comment by seocam** [comment]
The name of the repos are `puppet-environments` and `mobileapp`. I've unlinked `puppet-environments` and linked it back and now the milestones are working. I haven't done the same for `mobileapp` so you could investigate the issue.

**Comment by leonardfactory** [comment]
Same issue here. I can send you an email with the repo name if it helps.

**Comment by derrickreimer** [comment]
Hi @leonardfactory, please do! Thanks

**Comment by leonardfactory** [comment]
@djreimer sent!

I've tried unlinking the project and syncing github data with provided command in the interface.
Even actually changing (on GitHub) one issue milestone to not-recognized one, does not cause Codetree to refresh.
Furthermore, the issue still keeps listing under the old milestone.

**Comment by kareem** [comment]
@leonardfactory did you end up resolving this?  If not can you please email me with the repo name?  support@codetree.  Thx.

**Comment by kareem** [comment]
Closing for now.  @leonardfactory and @seocam if this is still giving you trouble please let me know here.  Thanks.
