### ISSUE TITLE
Issue counts not being updated for taskboard columns in milestones

### ISSUE THREAD

**Issue by phobeo** [codetree/feedback#185]
when checking the board view of a Milestone (navigate to Issues > Task Board > choose Open Task Board in a milestone), despite there being actual issues in a column, they all show issue count as zero:

![screenshot 2016-02-11 18 14 45](https://cloud.githubusercontent.com/assets/109575/12983938/ddffba64-d0eb-11e5-821f-af812b0ac6bf.png)

Would have expected that number to be the actual number of issues in the column. Is that not correct?

**Comment by derrickreimer** [comment]
Hi @phobeo - this figure is actually the sum of the size points in the column.
