### ISSUE TITLE
Sorting issues recently became a bit buggy

### ISSUE THREAD

**Issue by ajwaxman** [codetree/feedback#186]
I'm trying to re-order issues in a list view organized by assignee. Sorting works about 50% of the time, but there are a handful of issues that revert back to their original spot whenever I try and move them :pensive:

**Comment by derrickreimer** [comment]
That's no good :(. I'll take a look.

**Comment by ajwaxman** [comment]
I can email you a video via email if that'd be helpful. Just didn't want to post a video with our backlog on GH. Thanks!

**Comment by derrickreimer** [comment]
Sure, if it's not too much trouble that could be helpful for troubleshooting.

**Comment by ajwaxman** [comment]
Np, just send an email to support@codetree.com

**Comment by derrickreimer** [comment]
Alright, I reindexed your project ordering. Let me know if you are still seeing strangeness.

**Comment by ajwaxman** [comment]
Working well now! Thanks!!

**Comment by derrickreimer** [comment]
:+1: :tada:
