### ISSUE TITLE
Show repository name in milestone list

### ISSUE THREAD

**Issue by hgascoigne** [codetree/feedback#187]
I'd love it if the milestone list would prepend the name of its parent repository (similar to how it already does for issues). We are tracking many repos in CodeTree and if a milestone is named "v1.0," we don't have context for which project that is under. We are currently getting around this by putting the repo name in the milestone, but it's redundant when in GitHub. Thoughts?

Thanks guys!

**Comment by derrickreimer** [comment]
Hi @hgascoigne, Codetree actually aims to have milestones shared across all the repos linked to a project. For example, when you create a milestone through Codetree, it will create one with the same name in every linked repo. I actually think it's the right approach to prepend the repo name in the milestone if it only applies to specific repo.
