### ISSUE TITLE
A way to hide the Done column in the task board view

### ISSUE THREAD

**Issue by briangruber** [codetree/feedback#188]
In case I'm not interested in seeing all the done issues.

**Comment by wanderingmatt** [comment]
:+1:

Our team has a couple Milestones which we use for on-going Issues, like Maintenance. The Done column in those contain thousands of bugs and is fairly useless.

**Comment by kareem** [comment]
Agreed @WanderingMatt and @briangruber.  On our list to toggle it as you toggle the Backlog column.

**Comment by rstocker99** [comment]
Hi @WanderingMatt and @briangruber, we've deployed this to production. You can toggle the 'Done' column now in the same way that you toggle the 'Backlog' column.

**Comment by wanderingmatt** [comment]
👌
