### ISSUE TITLE
Drag-drop operation occasionally locks up the interface

### ISSUE THREAD

**Issue by realyze** [codetree/feedback#189]
When I try to move a card (any card) between columns, the source card disappears, mouse cursor turns into a fist and the system doesn't allow me to interact with anything on screen.

I'm on Mac 10.11.2, Chrome 48.

**Comment by derrickreimer** [comment]
Hi @realyze, that's no good. I'm having trouble reproducing this behavior. I haven't heard other reports either. Are you still experiencing this?

**Comment by realyze** [comment]
Hmm, no it seems to have fixed itself after I rebooted my Mac later that day. Might have been just a ghost in the machine sort of thing. Will report if it happens again.

**Comment by derrickreimer** [comment]
:+1:

**Comment by realyze** [comment]
So this is still happening. And quite often (like, every other day). It's incredibly frustrating.

**Comment by derrickreimer** [comment]
@realyze that's no good. I will try my best to reproduce this. If you notice any pattern of behavior that ultimately leads to this happening, please let me know. I will reopen this ticket to track progress.

**Comment by kareem** [comment]
Haven't been able to repro this behavior and haven't gotten any other reports.  Going to close the ticket.  @realyze if this is still happening please let me know and I'll re-open.  Thanks.
