### ISSUE TITLE
Support for private repositories

### ISSUE THREAD

**Issue by lexitorres** [codetree/feedback#190]
Is there any way to add private repositories to Codetree? All of our repos are private but we really want to use the tool!
Thanks,
Lexi

**Comment by derrickreimer** [comment]
Hi Lexi, you definitely can! Sounds like a permissions issue.

Are these private repos under a GH organization, and do you have [third-party application restrictions](https://help.github.com/articles/about-third-party-application-restrictions/) in place for this organization? If so, you should be able to grant access by going to your Applications page (https://github.com/settings/applications), clicking "Codetree", then clicking "Grant access" next to your organization under "Organization access".

Let me know if this does not solve it.
