### ISSUE TITLE
A stage should be able to have closed issues.

### ISSUE THREAD

**Issue by kangaroo5383** [codetree/feedback#191]
Our current process is such:

in progress / open
resolve / open (in code review)
release / closed (issue is completed and will go out with the next release)
fixed / closed (in the latest internal build, assigned to issue creator to verified)
verified / closed (all done!)
rejected / open (nope, not fixed, try again!)

The reasoning is as follows:
- Our engineering team and non engineering are using github issues to keep track of issues
- Any issue that engineering is done with and don't have to look at anymore are closed, that decision correlates with how github interprets `fixes #[some issue number]` as closing an issue.

Our "done" stage is actually the verified / closed combination.
The current workaround is to use your short cuts feature instead of stages, but I would really like to use the stages as the task board is quite useful.

Love your product so far, it's the best I've seen so far in managing multiple github repos.  Do let me know if it's possible to / there are plans to enable customize the "stage" filters as requested above, or if you have any additional suggestions in regards to our workflow.

**Comment by derrickreimer** [comment]
Sorry to leave you hanging @kangaroo5383 -- this one somehow slipped into my inbox archive. This has come up before -- let me see what I can do and I'll keep you in the loop. Glad to hear CT is working out well for you!

**Comment by kangaroo5383** [comment]
Thank you so much @djreimer, appreciate you looking into it!  Our team is really loving it after testing a number of solutions, really great work here, very glad we found CT.  Look forward to hearing from you.

**Comment by kangaroo5383** [comment]
@kareem  #212  is not actually related to this issue but it's simply a delay on the stage label removal, possibly fixed by not removing tags that are added after the issue is closed.  The suggested fix makes logical sense.  

The delayed removal of the label ( #212) is starting to cause major issues around our development as issues that are not properly labeled (aka being removed by codetree because of the delay) is slipping through the crack.  It's causing enough disruption that the continual neglect of the issue will lead us to consider other options such as gitlab etc in order to support our growing team.

**Comment by kareem** [comment]
Hi @kangaroo5383 we want to solve your problem but want to fully understand your use case before acting.  Perhaps I'm not understanding correctly.  Could you help clear this up (question originally in #212):

The original intention was that Closed issues sit at the end of your workflow.  I sounds like some of your issues go through this workflow: Issue Closed Closed -> Release (Issue is Closed + release label) -> Fixed (Issues is Closed + fixed label). 

Is that accurate?

If so can you help me understand why you have closed issues with labels, instead of closing your issue once it's launched?  The idea is that custom stage labels get removed when an issue is Closed, so an issue wouldn't have labels assigned after it's Closed and still be part of the workflow.  

Thanks!

**Comment by kareem** [comment]
BTW - re #212 the reason this is related, I think, is b/c if you don't touch closed tickets after they're closed (e.g. by adding a `release` label to a closed ticket) then Codetree's behavior doesn't need to change (e.g. stages don't need to have Closed Issues b/c Closed issues are only in the done stage).

**Comment by kangaroo5383** [comment]
> If so can you help me understand why you have closed issues with labels, instead of closing your issue once it's launched? 

In my original comment above
"Any issue that engineering is done with and don't have to look at anymore are closed, that decision correlates with how github interprets fixes #[some issue number] as closing an issue."

Github's mechanism for closing an issue via commit message in the form of "closes #1234" is a natural way for our merging and committing to signal that that was the final commit for a particular issue.  This workflow has worked well for out team for the past 2 years.  

> Codetree's behavior doesn't need to change

It sounds like it does, and there's just bad logic here.  It doesn't make sense why STAGE 1 -> close -> STAGE 2 would lead to both STAGE 1 and STAGE 2 being removed once an issue is closed.  The right implementation would just remove the last stage label right before closing.  The problem I'm experiencing is a sideeffect of codetree's issue state not updating fast enough.  If I close the issue manually in codetree, the label "RESOLVED" is removed immediately and I can get on with my life and add a label that won't get magically removed, however it is from the delayed update that codetree is removing a label that I added AFTER I closed the issue.

**Comment by kareem** [comment]
Hi @kangaroo5383 can you help me understand something?  It sounds like you close issues mid-workflow for two reasons:
1. Because your devs want to use the "fixes" syntax from the command line
2. So your devs don't see work that's already done in their queue

Is there another reason you close tickets mid-workflow, or is it for the above convenience / filtering reasons for your devs?

Thx

**Comment by kareem** [comment]
@kangaroo5383 we have a feature in the pipeline that will let your devs use a commit verb like e.g. "resolved #123" to advance tickets through stages.  Are you up for a short chat to make sure it'll help you with this?  

Related to this ticket - we're going to close it b/c Codetree has a series of stages that are a linear progression from Open to Closed with stage labels in between.  The workaround is to have non-custom-stage labels assigned to Closed issues.

**Comment by kareem** [comment]
@kangaroo5383 related - I think that the feature we'd like your insight on will help your workflow issue. Let me know if you're up for a short conversation where we can show you some mocks.  Thx.

**Comment by kangaroo5383** [comment]
@kareem thank you for the follow up, apologies on the lack of reply as I didn't see the previous comments.  It would be great to chat and check out the new feature.  "commit verb" as you describe definitely sounds interesting, let me know when is a good time. 👍
