### ISSUE TITLE
Due date dropdown sporadically stops working in Safari

### ISSUE THREAD

**Issue by TimonVS** [codetree/feedback#193]
When I click on the dropdown to change the due date and click on `change...` the date input doesn't appear in Safari. If I try to click on the dropdown after that, nothing happens anymore (the dropdown doesn't open anymore).

Video demonstrating the bug: https://vid.me/rPz4

**Comment by derrickreimer** [comment]
How odd...first report of this one as well.

**Comment by derrickreimer** [comment]
I'm having trouble reproducing this. Tested on Safari 9.0.3 (11601.4.4). Which version are you on?

**Comment by TimonVS** [comment]
Safari 9.1 (11601.5.17.1). It only happens sometimes though, it's really strange.

**Comment by derrickreimer** [comment]
The good news is I have reproduced it. The bad news is for the life of me I can't see what causes it. As you observed, it only happens sometimes and for no apparent reason. I will keep working on this, but it seems like a bug in Safari.

**Comment by leonardfactory** [comment]
Happening to me too. It happens when I create a new Milestone on CodeTree. Even reloading doesn't show the input. I've found that updating the Due Date on Github, and then switching back to CT, clicking on _Change.._ makes the input available again.

**Comment by kareem** [comment]
Will try and repro this.

**Comment by kareem** [comment]
We've repro'd this but can't figure out why it's happening.  More investigation needed.

**Comment by ac21** [comment]
implemented new due date functionality earlier this year; no longer reproducable
