### ISSUE TITLE
Wrong due date is shown

### ISSUE THREAD

**Issue by TimonVS** [codetree/feedback#194]
When selecting a due date, the due date shown in the UI is a day before the actual due date. The Github milestone shows the correct due date which was selected in the date input.

Example:
Github:
![](https://i.imgur.com/48gB6si.png)

CodeTree:
![](https://i.imgur.com/R8FbxPY.png)

**Comment by derrickreimer** [comment]
Looks like a time zone issue -- I will investigate.

**Comment by TimonVS** [comment]
@djreimer I see that you've closed the issue. But the issue is still there for me. Or is the version with the fix not deployed yet? :)

**Comment by derrickreimer** [comment]
Hm that's odd. Same milestone showing the wrong date for you?

On Sunday, April 10, 2016, Timon van Spronsen notifications@github.com
wrote:

> @djreimer https://github.com/djreimer I see that you've closed the
> issue. But the issue is still there for me. Or is the version with the fix
> not deployed yet? :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/codetree/feedback/issues/194#issuecomment-208042513

## 

Derrick

**Comment by TimonVS** [comment]
No, it's a new milestone actually.

**Comment by derrickreimer** [comment]
Can you send me the name? Feel free to email if you are more comfortable with that. It seems like GitHub attempts to set the due date to midnight in the time zone in which the user creating the milestone is located. We are now auto-detecting the time zone of the acting user, so it should be in line. Also, what time zone is your computer set to (assuming you were the one who created the milestone)?
