### ISSUE TITLE
Click and hold to delete is confusing

### ISSUE THREAD

**Issue by TimonVS** [codetree/feedback#195]
'Click and hold to delete' is really confusing for new users (my coworkers).
I think a better solution would be to be able to click once then the button will turn red and contain the text "Are you sure?".

Example.: http://codepen.io/timonvs/pen/oxoyLm

**Comment by xenithorb** [comment]
-1 

I prefer exactly the way labels are handled right now

**Comment by maxheld83** [comment]
yeah, I stumbled upon this too – thought I couldn't delete labels as documented in #270.

I find this somewhat unusual for a web app, I'd prefer a way to quickly revert the action, if done in error.

Also, the discoverability is a little glitchy on Safari, I think ... the button just jumps around if I short click.

**Comment by ac21** [comment]
+1 - this is confusing.  adding to 2019-Q4 roadmap

**Comment by ac21** [comment]
needs codetree/codetree#2712

**Comment by sachinkum123** [comment]
resolved by #2712

**Comment by ac21** [comment]
released
