### ISSUE TITLE
Duplicate modal overlay

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#196]
Clicking on one of the default views immediately prior to filing a new Issue results in a duplicate modal overlay which cannot be excused.
##### REPRO
1. Click **Issues** or **Pull Requests** from the left sidebar.
2. Click **New Issue**.
3. Close the new _New Issue_ modal.

**Comment by derrickreimer** [comment]
Thanks for the repro steps! I see what's happening. Now for the fix...

**Comment by derrickreimer** [comment]
Should be fixed now
