### ISSUE TITLE
Sometimes you click to modify sometimes you click to filter

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#197]
Some subjective UX criticism.

Now that you've taught me to re/assign new issues from the _New Issue_ modal by clicking on the Github username here...

![screen shot 2016-04-06 at 2 30 11 pm](https://cloud.githubusercontent.com/assets/11926/14333597/68ba75ca-fc04-11e5-8c5b-0aaf1e0519c2.png)

I constantly attempt to re-assign issues from list view by clicking on the Github username in the same way here...

![screen shot 2016-04-06 at 2 30 17 pm](https://cloud.githubusercontent.com/assets/11926/14333706/ee2bb142-fc04-11e5-95e8-eca59ea3f471.png)

But clicking on the username in that situation filters the view instead of displaying the Assignee modal. Bugs me every time.

**Comment by kareem** [comment]
@WanderingMatt agreed.  This is on our list.

**Comment by kareem** [comment]
Hi @WanderingMatt just (re-)launched the ability to change an issue's milestone and assignee from the List view, which might make things a little easier for you.  

I hear you on the UX issue you bring up (clicking to Assign in Issue Modal vs. clicking to see a list of issues for that user in List View).  It's on our list to address. The newly-launched feature doesn't change that behavior but should guide you towards doing what you want (assigning) in the list view.

**Comment by kareem** [comment]
@WanderingMatt Just deployed a fix for this.  Now when you click in the modal, you get the label picker.

![2016-12-09 at 2 58 pm](https://cloud.githubusercontent.com/assets/26123/21067425/fb53b7ce-be1f-11e6-9e29-517b5e923c16.gif)

**Comment by kareem** [comment]
BTW, here's the pattern:
* when you click in the issue modal, you are clicking to change things.  
* when you click OUTSIDE the issue modal, you're clicking to view/filter things.  If this isn't true, there's a UI affordance to let you know that you're clicking to change.
