### ISSUE TITLE
Screen remains in modal after closing dialog

### ISSUE THREAD

**Issue by adro718** [codetree/feedback#198]
Issue:
After I close a modal dialog for an issue in code tree I can't access the list view as the transparent gray is still blocking me. I need to refresh before I can interact with the screen.

How to reproduce:
Launch Modal and close modal and see if overlay of screen is still there. 

Note: This doesn't always happen.

**Comment by derrickreimer** [comment]
Ergh...sorry about that. I recently upgraded bootstrap modal library and it
looks to be buggy. Will address soon.

On Wednesday, April 6, 2016, Alex Robinson notifications@github.com wrote:

> Issue:
> After I close a modal dialog for an issue in code tree I can't access the
> list view as the transparent gray is still blocking me. I need to refresh
> before I can interact with the screen.
> 
> How to reproduce:
> Launch Modal and close modal and see if overlay of screen is still there.
> 
> Note: This doesn't always happen.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/codetree/feedback/issues/198

## 

Derrick

**Comment by derrickreimer** [comment]
Duplicate of #196
