### ISSUE TITLE
Sorting issues within Milestones

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#20]
It would be incredibly useful to be able to sort issues in a given milestone by different criteria including Assignee, #/Creation Date, and Recently Updated. Ideally, it would be nice to be able to simply click on the table header to change the sort.

**Comment by derrickreimer** [comment]
Thanks Matt! I agree. This one is in the queue. Will keep you informed.

**Comment by ajwaxman** [comment]
Was just about to open an issue with the same request. It'd be awesome to be able to sort the tables in a similar manner as GitHub's `/issues` UI (although I personally have never used least / most commented much) :

![](http://cl.ly/doWD/Image%202015-11-13%20at%201.45.55%20PM.png)

**Comment by ezra-g** [comment]
It seems worth noting that Github recently added the ability to [sort issues within a milestone](https://github.com/blog/2206-reorder-issues-within-a-milestone).
