### ISSUE TITLE
Error in milestone ordering

### ISSUE THREAD

**Issue by leonardfactory** [codetree/feedback#200]
In my project Milestone are actually ordered **not** by version number.
Milestones created before still appear before the new one, even if it has a lower version number (i.e. `v0.5.1` appears after `v0.6.0`)

I can give more info in private if necessary

**Comment by derrickreimer** [comment]
Hi @leonardfactory - I believe this is expected behavior. Milestones can be ordered manually (just like issues). When a new milestone is created, it is placed at the bottom of your milestone list. You can grab the sort handle to reorder as needed.

**Comment by leonardfactory** [comment]
Thank you! I completely missed out the `Milestone` & `Labels` sections on the left, my bad!
As everytime, awesome job. Thanks again.

**Comment by derrickreimer** [comment]
🎉
