### ISSUE TITLE
Size is not propagating to issues title

### ISSUE THREAD

**Issue by dallasgutauckis** [codetree/feedback#201]
When setting task size on an issue, it is not updating the GitHub issue title any more… at least on our project.

**Comment by derrickreimer** [comment]
Hi Dallas, looks like you may not have received the email notification about this. Check out #155 for the latest.

**Comment by dallasgutauckis** [comment]
Thanks @djreimer — can confirm I didn't receive an email from that. I saw that issue but didn't read it in full to see that it had been disabled. Apologies for the dupe.
