### ISSUE TITLE
Show milestone due date in list view

### ISSUE THREAD

**Issue by kangaroo5383** [codetree/feedback#202]
I thought that this was already a feature but it seems to not be working correctly all the time.  We have changed some milestone deadlines on a couple projects and they are now not listed in any discernible order.  

An additional suggestion - it would be very useful to have the deadline displayed when grouped by milestone as well.

**Comment by derrickreimer** [comment]
Hi @kangaroo5383!

> We have changed some milestone deadlines on a couple projects and they are now not listed in any discernible order.

I believe this is expected behavior. Milestones can be ordered manually (just like issues). When a new milestone is created, it is placed at the bottom of your milestone list. You can grab the sort handle to reorder as needed.

> An additional suggestion - it would be very useful to have the deadline displayed when grouped by milestone as well.

Sounds useful -- picturing this being displayed in the list view, correct?

**Comment by kangaroo5383** [comment]
> I believe this is expected behavior. Milestones can be ordered manually (just like issues). When a new milestone is created, it is placed at the bottom of your milestone list. You can grab the sort handle to reorder as needed.

Awesome thanks, I didn't think to look there.  It's definitely a better implementation to allow room for custom ordering than enforcing chronologically.

> Sounds useful -- picturing this being displayed in the list view, correct?

Yes exactly.  Near/in the header area etc. that would be awesome.

**Comment by kareem** [comment]
Hi @kangaroo5383 just pushed this live today.  Thanks for the suggestion!
