### ISSUE TITLE
Cannot create a new issue - the "Create Issue" button is broken

### ISSUE THREAD

**Issue by jms21852** [codetree/feedback#203]
Chrome v49, OSX 10.11.3
<img width="381" alt="screen shot 2016-04-20 at 14 38 20" src="https://cloud.githubusercontent.com/assets/6922799/14687946/9cef80c2-0705-11e6-89a3-ff2e87ff55d0.png">

**Comment by derrickreimer** [comment]
Hmm I'm the same version of Chrome and I'm having trouble reproducing this. Is it still happening? Can you recall the sequence of events that lead up to this?

**Comment by derrickreimer** [comment]
I'm fairly certain this was a GitHub permissions issue. Should be resolved now.
