### ISSUE TITLE
Edit Labels Produces Empty Modal

### ISSUE THREAD

**Issue by tnoetzel** [codetree/feedback#205]
From /labels, clicking "edit" on any of the labels produces an empty modal, rather than a something that allows you to edit the name/color...

<img width="1226" alt="" src="https://cloud.githubusercontent.com/assets/1002744/15304568/174bff9a-1b8c-11e6-8e19-9ee6319a6773.png">

**Comment by derrickreimer** [comment]
Strange! Will investigate.

**Comment by kareem** [comment]
@tnoetzel can't repro this right now and going to close it.  Can you please let me know if it's still happening and we'll investigate again?

Thanks
