### ISSUE TITLE
Filter by the date the issue was created

### ISSUE THREAD

**Issue by nZac** [codetree/feedback#209]
It would be great to be able to run a query like "issues created last week" or arbitrary date ranges

**Comment by kareem** [comment]
Good suggestion, thanks @nZac.  Curious - what are you trying to do with that information?

**Comment by nZac** [comment]
Hi @kareem!

Great question. Every week I send a report to our clients about what is coming up for the next week, a part of that is going through our issue list and adding whatever issues were created by developers. 

Having a shortcut for "Created last week" would be very helpful. Right now I just go to GH and put `created: >YYYY-MM-DD`.

**Comment by kareem** [comment]
@nZac Makes sense, thanks!  We definitely think the search and querying interface could use some love and your suggestion slots in nicely there. I'll add it to our list for consideration in upcoming builds.  

Cheers!

**Comment by rstocker99** [comment]
related to #214

**Comment by ac21** [comment]
closing for now due to lack of interest.  most community interest was in sorting by created_at and updated_at and this was enabled over the summer
