### ISSUE TITLE
Delete a shortcut

### ISSUE THREAD

**Issue by lightcap** [codetree/feedback#21]
There doesn't seem to be a way to delete a shortcut once it's created.

**Comment by derrickreimer** [comment]
Sorry for the confusion. To delete/reorder shortcuts, head to Settings > Shortcuts. The settings link can be found in the dropdown that appears when you click the "Issues" heading in the left sidebar.

![settings](https://cloud.githubusercontent.com/assets/341387/5649166/aa3325ba-9648-11e4-86b3-60633a59e6bb.png)
