### ISSUE TITLE
Assigning labels from Codetree results in duplicates

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#210]
This started happening somewhat recently. If I add a label from Codetree, it shows up twice.

![screen shot 2016-07-19 at 2 40 10 pm](https://cloud.githubusercontent.com/assets/11926/16967679/1da81aa8-4dbf-11e6-85e7-145b7155c0ee.png)

**Comment by arifb** [comment]
Thanks Matt, someone on team will look into this. Are you seeing the same thing if you view one of these issues on GitHub?

**Comment by wanderingmatt** [comment]
@arifb Nope. Everything seems normal over on the Github side.

**Comment by kareem** [comment]
Hey @wanderingmatt looking into this in more depth.  Are you still seeing this behavior?

**Comment by wanderingmatt** [comment]
Yep.

![screen shot 2016-08-25 at 12 40 30 pm](https://cloud.githubusercontent.com/assets/11926/17983387/29c3fa22-6ac1-11e6-8b2a-8740b455316c.png)

**Comment by kareem** [comment]
That's no good Matt, sorry you're having that issue.  We'll take a look.

On Thu, Aug 25, 2016 at 12:41 PM, Matthew Anderson <notifications@github.com

**Comment by wanderingmatt** [comment]
FWIW, we've noticed a few other saving/closing problems with the issues affected by duplicate labels. After a little digging, I noticed that the duplicate labels only appear to be happening with issues that are filed in a repo that we renamed.

Just wanted to pass that along because I have a hunch that the cause of this issue might actually be something with not handling renamed repositories correctly.

**Comment by rstocker99** [comment]
@WanderingMatt Thanks! That's super helpful. Thanks for passing along.

**Comment by rstocker99** [comment]
Having trouble reproducing this.

**Comment by wanderingmatt** [comment]
Let me know if I can help in any way.

**Comment by kareem** [comment]
Thanks Matt.

**Comment by rstocker99** [comment]
Fix for this has been pushed.

**Comment by ac21** [comment]
closing as fix was pushed
