### ISSUE TITLE
Scrollbar periodically vanishes

### ISSUE THREAD

**Issue by tom-ld** [codetree/feedback#213]
Using Chrome on a Windows 10 laptop.

After modifying an issue, dismissing the dialog box returns me to a screen where the scrollbar has vanished off the right, and using the scroll wheel on the mouse doesn't do anything.  However, refreshing the window restores the scrollbar and allows scrolling with the mouse wheel. This doesn't happen all the time.

This mostly seems to happen when the issue is reassigned to a new owner (in the right side of the dialog box). Initially creating an issue, or entering a comment to an existing issue, does not seem to cause the problem.

Screenshot of normal window with scrollbars:

![has scrollbars](https://cloud.githubusercontent.com/assets/11142402/17821931/0bb2ca8e-6609-11e6-8ab7-54d67830243c.jpg)

Screenshot of window after dismissing dialog box, no scrollbars:

![no scrollbars](https://cloud.githubusercontent.com/assets/11142402/17821937/1851b6ec-6609-11e6-8826-280f61f1755a.jpg)

**Comment by rstocker99** [comment]
Hi Tom thanks for the repo steps on this bug. A few other folks have reported this problem and we've had a lot of trouble tracking it down. With the above steps we've figured out the issue. We're working on a fix. We'll let you know once we've pushed it to production.

**Comment by talex1962** [comment]
Thanks!

**Comment by rstocker99** [comment]
We've deployed a fix for this.
