### ISSUE TITLE
Lists of open issues should have a creation date column

### ISSUE THREAD

**Issue by tom-ld** [codetree/feedback#214]
It is frequently very useful to know the "creation date" for an issue, especially when trying to search for an issue in a forest of them without a keyword to search on. For example, a developer may want to search for "the issue that Dan created last Friday", having forgotten exactly what the title was. If there is a column on the list view showing the creation date, one could sort on this, filter by a date range, and quickly locate such an issue.

**Comment by rstocker99** [comment]
Agreed creation date can be super useful. You mention two parts here:
1. Filtering by creation date
2. Sorting by creation date

Right now neither list view or board view offer any sorting other than by priority. Perhaps some sorting would be useful but would just having the ability to filter by creation date solve your scenario? I.e. if you could click "Add a filter" and "Created Date" showed in the dropdown?

**Comment by talex1962** [comment]
Actually maybe I overstated the filtering case ... it's just me personally, but I rarely have the patience to enter a filter expression when there's less than a page of anything to search through. I simply click on the column header to sort, then look down the list and use the filter in my brain.

Filtering by a creation date WOULD solve most problems, albeit a little less conveniently. If it is more convenient to implement it this way, that would work.

**Comment by ac21** [comment]
closing for now due to lack of interest.  most community interest was in sorting by created_at and updated_at and this was enabled over the summer
