### ISSUE TITLE
Label assignments sometimes appear twice in the history

### ISSUE THREAD

**Issue by tom-ld** [codetree/feedback#215]
Adding multiple labels (particularly 3, it seems) occasionally causes all the label assignment to appear twice in the history. See this JPEG:

![doubled labels 2](https://cloud.githubusercontent.com/assets/11142402/18037514/4bd10da4-6d3b-11e6-985e-f6fb62cfb248.jpg)

This is only mildly annoying, but I thought I'd point it out. (It's clearly impossible for me to have added the labels, then removed the labels, then added all the labels back in the same order again - if so, where are the history entries for the removed labels? And anyway I didn't do that.)

By the way, I fail to see the value in diligently pointing out all the label adds and drops in the history of an issue. Assignments, milestones, comments, etc. are useful so we can point the finger at each other. But changes to labels?

**Comment by kareem** [comment]
Hi @tom-ld we've seen a potentially related problem before (codetree team - see #210).

Are you able to reproduce this reliably?

Can you help us debug this?  It would be super helpful if you could share a screenshot of GitHub showing the label adds and drops for this issue.  Feel free to email it in - support@codetree - if you're not comfortable posting publicly.    

Thanks!

**Comment by tom-ld** [comment]
Hi, Kareem,

Unfortunately it's not reproducing. I tried several different workflows and it does not seem to happen. It also occurs only on a few of the 70-ish bugs in the database.

Here is the screenshot for GitHub for an example of one of these duplicate-label things:

![multi-tags 1](https://cloud.githubusercontent.com/assets/11142402/18062788/269a5908-6ddd-11e6-92e0-28bb953c0786.jpg)

Here is the corresponding screenshot for Codetree:

![multi-tags 2](https://cloud.githubusercontent.com/assets/11142402/18062798/3059d70c-6ddd-11e6-87a5-1d5326ecbcc4.jpg)

At first glance it doesn't look like Github has multiple labels assigned in its own history. Strange.

It could be that the issue has to sit for a while in Github before assigning labels will cause duplicates in the history. All my attempts at reproducing it were over the course of a few minutes, for obvious reasons. That's just a guess, though. Could be some weird API problem.

**Comment by kareem** [comment]
Hi Tom,

Very strange.  This is helpful for diagnosis though, thanks.  We'll see if
we can repro.

**Comment by ac21** [comment]
No longer observing this behavior - closing for now
