### ISSUE TITLE
Change filter bar to let customers select "Issues and/or Pull Requests" when in task board

### ISSUE THREAD

**Issue by christopher-francisco** [codetree/feedback#216]
Currently there is no UI element to click to let the **task board** show pull requests too alongside filters. 

The navigation process is: Go to side bar -> clic on Milestones -> _clic on a milestone_ -> Change from _list_ to _task board_ -> here there is no link to show pull requests too.

It works if I append to the URL `&type=`, but it's not really convenient having to type it every time.

**Comment by rstocker99** [comment]
That's definitely annoying. I don't see any reason why the task board view shouldn't include the UI for changing the issue type filter just list list views. In the short term a possible workaround is to:
1.  Make the query in list view so you can include pull requests.
2. Toggle to board view. It will keep the '&type=' qs param.
3. Save a shortcut if you want to use this query regularly. The shortcut will include the type param.

**Comment by arifb** [comment]
@chris-fa This is pushed, you can now see PR's alongside issues (or on their own)
