### ISSUE TITLE
Support Github issue and pull request templates

### ISSUE THREAD

**Issue by mrleeio** [codetree/feedback#221]
**What?**

https://github.com/blog/2111-issue-and-pull-request-templates

Github allows you to create CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ which auto populate the markdown editor whenever a new issue or pull request is created.

**Why?**

Default templates allow project maintainers to ask for the appropriate information up front when triaging new tickets or reviewing pull requests.  Reduces the amount of back and forth to retrieve common information that should be included by all contributors.

needs codetree/codetree#2639

**Comment by arifb** [comment]
Interesting @mrleeio appreciate the vote on this feature. Could definitely see supporting ISSUE_TEMPLATE.md, will chat with team.

**Comment by parhelium** [comment]
+1

**Comment by cseidema** [comment]
+1

**Comment by thecp** [comment]
+1

**Comment by stefanlangerhebo** [comment]
![image](https://user-images.githubusercontent.com/26866609/31722734-2ae30da2-b41d-11e7-9009-d952aaf0a58a.png)

**Comment by ipoerner** [comment]
+1

**Comment by mmenschner** [comment]
![image](https://user-images.githubusercontent.com/10629021/31722621-dc9f3db4-b41c-11e7-98f0-5f05134c6119.png)

**Comment by kareem** [comment]
Hah, message received @mmenschner, @stefanlangerhebo, @thecp, and @cseidema.  Will +4 the request internally.

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21454522334
+1

**Comment by phagunbaya** [comment]
Will there be support to pick from multiple issue templates ?

**Comment by ac21** [comment]
@phagunbaya - yes, it’s on our roadmap.  Seems this is bubbling up, so will discuss with team about changing the current prioritization

**Comment by kelada** [comment]
Using github templates via codetree would be a killer feature for my team. Specifically, being able to set a default template for Epics and a different one for Issues (based on the repo)
 
+1

**Comment by HX-Javier** [comment]
+1

**Comment by owap** [comment]
Hello! We spend $200/mo using codetree and would really, _really_ like to be able to use issue templates.  Really.

Please consider upping the priority and not letting it slide back any further!

**Comment by ac21** [comment]
prioritizing a spike to understand LOE

**Comment by CatalinaMoisuc** [comment]
@ac21 any news on this? It would be really really nice to have it!

**Comment by ac21** [comment]
@catalinaMoisuc - we have completed and testing in private beta.  Would you like to beta this?

**Comment by blladnar** [comment]
@ac21 Is this out of beta now? I have some templates set up in our Github repo but don't know how to get them to show up.
