### ISSUE TITLE
"Add milestone" field looks like the search input

### ISSUE THREAD

**Issue by Reinmar** [codetree/feedback#222]
![image](https://cloud.githubusercontent.com/assets/156149/20101586/edeb47de-a5c2-11e6-9bb1-cf54fd98867f.png)

I already couple of times created new milestones when I was trying to search for some issues. That's because it's very similar to:

![image](https://cloud.githubusercontent.com/assets/156149/20101620/15556282-a5c3-11e6-9f92-73f1c4cfbd54.png)

The minimum will be to style it significantly different. But the best option is to move it somewhere else.

**Comment by ac21** [comment]
Has not come up in user feedback; closing for now
