### ISSUE TITLE
Ordering shortscuts is broken

### ISSUE THREAD

**Issue by p8** [codetree/feedback#224]
When I try to move the bottom shortcut to a higher level it doesn't work

**Comment by arifb** [comment]
Hi @p8, thanks for the report, I'm able to repro trying to reorder global shortcuts. The shortcut I'm trying to move snaps back to old position. We'll have a look.

**Comment by arifb** [comment]
Hi @p8 this has been fixed and pushed, sorry about the delay.

**Comment by p8** [comment]
Thanks! Works great!
