### ISSUE TITLE
Set size from the Issue Modal

### ISSUE THREAD

**Issue by nlazarov** [codetree/feedback#226]
When we do the poker planning we set extensively the size field.

From the issues list I only need to add the value in the input.

However it is not easy to set it from the issue modal window - I need to select it from the tag list. It would be easier if the size field from the right pane of the modal view had the same input.

**Comment by arifb** [comment]
Hi @nlazarov. We agree with you and it's already on our list. You'll see this change soon.

**Comment by kareem** [comment]
Launched this last week @nlazarov: https://headwayapp.co/codetree-changelog/change-issue-size-from-the-modal-14174
