### ISSUE TITLE
A count of filtered issues would be very helpful

### ISSUE THREAD

**Issue by tom-ld** [codetree/feedback#227]
I frequently set filters in Codetree when assigning tasks to people: e.g., filter on all major issues for a given milestone that don't have the label "Verify" and are assigned to a particular person.

I find myself manually counting these issues to be able to tell someone "Glenn, you have 10 issues you need to take care of this week", or when I'm determining whether it is possible for us to meet the milestone or whether there are too many issues to resolve.

It would be great to add the count of issues that made it through a filter, such as:

      Showing list  of **63** open issues under Production Release  milestone

**Comment by arifb** [comment]
Agreed @tom-ld I think this would be super useful. Have just pushed the change, let me know if this is not what you were looking for.

**Comment by tom-ld** [comment]
Works GREAT! I didn't even realize you had pushed the change until I was thinking "wonder how many issues Andy has left to close?" and there on the header was the exact count I wanted.

Thank you!
