### ISSUE TITLE
cmd-i to open issue switcher also opens Mail.app from Safari

### ISSUE THREAD

**Issue by matthewlehner** [codetree/feedback#228]
In Safari, I thought I'd give the issue switcher a go – love the idea, but it's opening Mail.app (as well as the issue switcher)

I'm using the latest Safari Technology Preview on this side of things.

**Comment by rstocker99** [comment]
Well that's embarrassing isn't it! It was originally CMD-k but that's bound by default in Chrome on Linux. We've added CMD-k back so now both bindings will work. Give it a try when you get a sec and let us know what you think.
