### ISSUE TITLE
Moving issue to new milestone results in it dissapearing

### ISSUE THREAD

**Issue by electric-al** [codetree/feedback#229]
Steps:

1) Create new milestone in milestone screen
2) Go back to list view and create / edit an issue and assign to the new milestone.
3) Issue does not appear in list (if new) or disappears if you are moving milestone.
4) to make the new milestone appear, you need to refresh the page

Expected:

New milestone should appear in list view without refresh.

Cheers

**Comment by kareem** [comment]
👍 Agreed. Thanks Al.

**Comment by ac21** [comment]
resolved previously.  closing
