### ISSUE TITLE
Creating shortcuts was confusing to figure out

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#23]
FWIW, even the word ("shortcut") confused me.

My main difficulty though was with figuring out how they worked. The first time I used it, the UX made me think that I needed to create the shortcut and name it first, then set all of the filters. I created a couple of shortcuts in a row that were simply duplicates of the Issues view. At the very least, some explanation text would be helpful.

**Comment by derrickreimer** [comment]
Thanks, good feedback. We will work on refining this.

**Comment by jochenonline** [comment]
Can anyone explain HOW shortcuts work or what they even are?

**Comment by VinSpee** [comment]
"Shortcuts" are basically links to quick filters.

To create a shortcut:
1. Filter your issues exactly as you like. For example, add a tag such as "bug"
2. Press the "Create Shortcut" button in the sidebar.

Whenever you click that shortcut, it takes you to this filtered view.

In my case, I'm using tags as markers for large features within our application which all share a repo ("dashboard", "widget", "creator"). I've created shortcuts for each large feature label so I can quickly see what is going on with that particular piece.

**Comment by derrickreimer** [comment]
@VinSpee great explanation!

**Comment by aseemk** [comment]
Maybe the fix could be as simple as rewording "Create shortcut" to e.g. "Save shortcut" or similar. Maybe a tooltip on hover that clarifies, e.g. "Save the current view to a shortcut."

Related though: it'd be nice to be able to edit an existing shortcut, e.g. by re-saving with the same name, overwriting the existing one. The scenario is for a "current milestone" shortcut.
