### ISSUE TITLE
Limit on issues handled by Codetree?

### ISSUE THREAD

**Issue by tom-ld** [codetree/feedback#231]
I'm not sure if I'm going to be coming off like an idiot reporting this ... but for some strange reason Codetree stopped displaying issues from our repo after issue #550.

Here is the Github issues list:

![github](https://cloud.githubusercontent.com/assets/11142402/22813201/b5e45922-eefe-11e6-921d-8e30a86654d5.jpg)

I created a couple of test issues from Codetree, #558 and #559. They did not show up in Codetree at all. In fact the issue creation dialog box just hung there, with the fields grayed out. (The reason there are two identical test issues is that I clicked twice on the submit button, because nothing was happening in Codetree.)

Here is the corresponding Codetree issues list. Unlike Github there appears to be no way to show all the issues in numeric order irrespective of milestone, so you'll just have to look at the count of total closed and open issues at the top:

![codetree](https://cloud.githubusercontent.com/assets/11142402/22813233/135b434a-eeff-11e6-8153-b546a1e9111d.jpg)

Notice that Codetree seems to be convinced that there are only 550 issues. And indeed when I search for issue #550 I get:

![issue550](https://cloud.githubusercontent.com/assets/11142402/22813300/7d6479fa-eeff-11e6-92c9-fb0ba33e3546.jpg)

which is what I expect, but when I search for issue #559 (the last issue seen on the Github issues list) I get:

![issue559](https://cloud.githubusercontent.com/assets/11142402/22813311/93359caa-eeff-11e6-8696-468884669439.jpg)

So for some strange reason I can enter issues into Codetree, but it seems to hang, and I can see these issues in Github, but Codetree won't display it.

By the way Codetree also seems to have slowed way down now that we are at 550 issues. It takes a minute or two for anything to happen, including logging in.

The other developers are seeing this too.

Help?

**Comment by kareem** [comment]
Hi Tom,

Very strange.  I'll take a look and let you know what I find.  Sorry you
guys are seeing this.

**Comment by kareem** [comment]
Hi Tom,

Looks like we're having some issues that are causing slow response times and slow processing of inbound GH issues.  Apologies.  Working on it now.  Newly-created GH issues will get to Codetree, just not with their usual snappiness.  More soon.

**Comment by kareem** [comment]
Hi @tom-ld we've resolved the issue and perf should be back to normal, as should pulling issues from GH.  Please let me know if you see any other issues.  Thanks!

**Comment by tom-ld** [comment]
Hi, Kareem, all better now! Thanks for fixing this so promptly. Excellent job!

**Comment by kareem** [comment]
👍
