### ISSUE TITLE
Make the 'repository selector' slightly wider

### ISSUE THREAD

**Issue by electric-al** [codetree/feedback#232]
Any chance of making the repository selector when creating a new issue a bit wider? Some of our repos have a common prefix, and we can only read a few chars after them as it is!

In fact, I am currently running some custom CSS to tweak the new issue popup and make the right hand panel wider, as I find it all bit tight. I have:

```
.modal-dialog{
    width:1100px !important
}

.issue-form-main{
    width:800px !important
}  
       
.issue-form-sidebar{
    width:300px !important;
    margin-left: 799px !important;
}  
```

YMMV.

**Comment by arifb** [comment]
Ha! Love that running some custom CSS - I will look into this Al thanks.

**Comment by arifb** [comment]
Hey @electric-al - was just looking at this. I'm finding the repo name wraps, so I can see the whole repo name, see attached gif. Are you not seeing this behaviour? 

Or maybe I'm misunderstanding the issue you're describing.

![long-repo-name](https://cloud.githubusercontent.com/assets/40671/24268811/57669812-0fcc-11e7-84b5-2f4a92a929b5.gif)

**Comment by arifb** [comment]
@electric-al Going to close this as I haven't heard back - reopen if this is still an issue, thanks.
