### ISSUE TITLE
Unclear how to remove a dependency

### ISSUE THREAD

**Issue by rbetts** [codetree/feedback#236]
I created dependencies using the `needs` keyword in a comment added via the codetree UI. Removing those comment via the codetree UI, however, doesn't delete the dependency.

**Comment by kareem** [comment]
Hey @rbetts this isn't possible right now but it's very high up on our list.

**Comment by kareem** [comment]
@rbetts just launched this:

https://changelog.codetree.com/break-dependencies-25746

Thanks for the feedback.
