### ISSUE TITLE
user autocomplete on issue does not include the original author in drop down

### ISSUE THREAD

**Issue by jtarchie** [codetree/feedback#241]
Wanted:

Given I am commenting on an issue through the codetree modal,
When I try to autocomplete the `@` username of the issue author,
Then their name should appear in the autocomplete drop down.

**Comment by kareem** [comment]
@jtarchie this should work:

![2017-07-10 at 12 07 pm](https://user-images.githubusercontent.com/26123/28035150-63d5f204-6568-11e7-9eb0-e3a706752e49.gif)

Are you seeing something different?  One thing to watch out for is case-sensitivity.  If I searched for @Kareem in the above clip it wouldn't have autocompleted (we have an issue filed for that).

**Comment by bekervincent** [comment]
@bekervincent25
Lascahobas
Lahoye
Casse
Cayemites
ODVA
