### ISSUE TITLE
Moving issues between repos

### ISSUE THREAD

**Issue by imagolive** [codetree/feedback#243]
If you have a project with multiple repos then it is really easy to place an issue into the wrong repo.

Can you move the issue back into the correct repo somehow?

**Comment by arifb** [comment]
Hi @imagolive - yes, you can do that with codetree, using the quick actions hamburger menu to the left of the issue, see attached gif. 
![move-to-different-repo](https://user-images.githubusercontent.com/40671/30335974-9340a2d4-9798-11e7-9d2a-7d1ece2eb1cc.gif)
