### ISSUE TITLE
Cannot unlink repository which doesn't exist any more on GH

### ISSUE THREAD

**Issue by Reinmar** [codetree/feedback#244]
When I try to unlink a repository which I previously deleted on GH I get 404:

POST https://codetree.com/projects/***/repositories/*** 404 (Not Found)

**Comment by Reinmar** [comment]
I wouldn't mind that much if issues from this deleted repository weren't cached by Codetree and displayed on the issue list.

**Comment by ac21** [comment]
@Reinmar - closing now now - as this should be resolved
