### ISSUE TITLE
Milestone dragging does not work when page is scrolled

### ISSUE THREAD

**Issue by warpech** [codetree/feedback#257]
Steps to reproduce:

1. Go to your Codetree project milestones list
2. Make sure there is enough milestones to require scrolling of the page to see all of them
3. Scroll the page down to see the last milestone
4. Drag the last milestone up

Expected

Milestone dragging should work the same way it works when the page is not scrolled. 

Actual

The "ghost" of the dragged milestone is not visible when the page is scrolled

**Comment by kareem** [comment]
Hi @warpech thanks for the bug report.  I've verified this is an issue and will add it to our queue.

**Comment by ac21** [comment]
@warpech - this was recently addressed in a milestone and list view refactoring
