### ISSUE TITLE
Input on the top of the Milestones list should be for filtering, not for adding

### ISSUE THREAD

**Issue by warpech** [codetree/feedback#258]
On the top of the milestones list there is an input field. In my opinion, it should be for filtering of the milestones, not for adding of a new milestone. My reasoning:

1. It is misleading to have "filtering" input in the Issues list but an "creating" input in the Milestones list. I have created few milestones by mistake when I thought I will am filtering.
2. I have a lot of milestones and filtering would be very useful.

![image](https://user-images.githubusercontent.com/566463/38485840-7b8c027c-3bdb-11e8-908e-da8dafd8ff2a.png)

**Comment by kareem** [comment]
Thanks @warpech.  Agreed this is not optimal.  Not high pri but it's in our internal queue.

**Comment by ac21** [comment]
@warpech - changed the `add Milestone` UI and this field no longer exists.  closing
