### ISSUE TITLE
Add "close" action to issue modal

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#26]
I imagine that you are trying to handle the ability to quickly create multiple issues in a row; however, there should be an option to create a single issue and dismiss the modal in a single click. Typically, I would expect this to be handled through separate buttons — "Create" next to "Create and Add Another" or something. In addition, and especially for the "Create and Add Another" path, the modal needs a close and/or cancel button. In my experience, hitting escape or clicking on the overlay is not the most noticeable option for the average user.

**Comment by VinSpee** [comment]
I think these are two separate issues.
1. Adding a visual close action to the "create issue" modal.
2. Add new functionality to "Add another"

I think 1 is definitely fair - adding an additional affordance is nice for the less inclined (like our Customer Success team). 

I think 2 is heavy-handed and unnecessary. The additional cognitive load of figuring out what the difference between "Create" and "Create and Add Another" is will be way worse than closing the modal. I think you should avoid complicating features whenever possible and love the way it's currently implemented.
