### ISSUE TITLE
Does burndown chart consider size of issues?

### ISSUE THREAD

**Issue by felixfbecker** [codetree/feedback#261]
## Background
Some users and projects use issue size as part of their workflow, however, the burndown chart only allows for counting of issues.  

## User comment
The Y axis label of burndown charts says "Issue Count" - I would expect it to respect the size of issues like https://github.com/radekstepan/burnchart does

## Solution
add a toggle to use issue size in burndown;  only show the toggle if display issue_size is enabled and default to using issue size if enabled

### AC1: current behavior for 
Given I am a user
and my project setting `enable point estimates` is `false`
when I go to burndowns 
and select a valid milestone
then I should see the burndown chart by issue count

## AC2: point estimate burndown charts
Given I am a user
and my project setting `enable point estimates` is `true`
when I go to burndowns 
and select a valid milestone
then I should see the burndown chart by total point estimates
and I should see a toggle (point estimate vs issue count) defaulting to point estimate

## AC3: activating toggle
Given I am a user
and my project setting `enable point estimates` is `true`
and I go to burndowns 
and select a valid milestone and toggle (point estimate vs. issue count)
When I toggle to issue count
then I should see the burndown chart by issue count

**Comment by mleffler** [comment]
Agreed.  Having a burndown for number of issues is not useful at all, and defeats the purpose of sizing and getting a sense as to how the team is doing.  

https://en.wikipedia.org/wiki/Burn_down_chart

Please base the burndown on size - "Sum of Task Estimates", which is the definition of a burndown chart.

**Comment by kareem** [comment]
Thanks @mleffler and @felixfbecker.  Issue sizing is actually an optional Codetree feature and not everybody has it turned on.  But we hear you loud and clear - supporting points was a "v1" feature that we decided to cut.  It's definitely on our list.

**Comment by ac21** [comment]
+1 from @cricketts

**Comment by ac21** [comment]
+1 - @maxthoursie

**Comment by shlomi-nx** [comment]
@ac21, when could we expect this to go live? During our evaluation this feature came at a high priority from our managers

**Comment by ac21** [comment]
@shlomi-nx It's in our current sprint, so I'd expect it by 4/12.

**Comment by shlomi-nx** [comment]
@ac21 any news on this?

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21729993302
+1

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/23664174988
+1

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/24492097319
+1
