### ISSUE TITLE
Double quotes not escaped when filtering by epic name

### ISSUE THREAD

**Issue by taggartbg** [codetree/feedback#262]
When hitting the `/issues` endpoint and passing a query string for the epic, it will not escape the `"` character, and results in a server error:

<img width="614" alt="screen shot 2018-04-17 at 6 51 06 pm" src="https://user-images.githubusercontent.com/4722966/38907353-532b3ca8-4270-11e8-9318-d0872b3fe95f.png">

Even when I pass `%22`, it gets turned into a `"` and errors out.  This does not happen for single quotes or other special characters that should be URI encoded.

Github allows for quotes in issue names, so this breaks existing issues that are pulled into codetree.

Test cases:
- `https://codetree.com/projects/<project>/issues?epic="foo"` errors
- `https://codetree.com/projects/<project>/issues?epic=%22foo%22` redirects to the above and errrors
- `https://codetree.com/projects/<project>/issues?epic=foo` works fine

**Comment by ac21** [comment]
@taggartbg - no longer reproducible.  closing for now
