### ISSUE TITLE
BUG: In Task Board view, need a column that shows all issues not labeled to show in another swim lane

### ISSUE THREAD

**Issue by mleffler** [codetree/feedback#264]
The Backlog column in Codetree, in my mind, is broken.  

If I go to Task Board in a milestone, the Backlog column (which I can now choose to not display, thank you), but it shows all tickets - not just the tickets in that milestone.  They are ordered all over the place, and you cannot actually see what is in the milestone (Sprint).

This column should show all issues assigned to the milestone that are Open, with no label putting them in a defined swim lane.  The issue number at the top implies that is all that should display - but all issues are displayed.

To deal with this, we had to define another label (ugh) called Planned.  My concern about this is that if any ticket ends up in that milestone, but not with one of those labels defined, the issue will disappear from this view, simply by someone changing a label and accidentally marking it to be a status we have not defined to show in a swim lane.

So - please make the Backlog column in a milestone do what it is supposed to - only show the Backlog for that milestone, not everything.

**Comment by geoffturk** [comment]
I am experiencing the same issue.

List view works fine:
`Showing list of 4 open issues under MyMilestoneName milestone`
I see the 4 issues that have that milestone assigned to them.

But when I switch to board view:
`Showing task board of 4 issues under MyMilestoneName milestone`
I see my one issue in the Planned column, but there are a number of other issues (48 in fact) in the Backlog column other than the 3 that are actually pegged to that milestone.

The list view for milestones works as expected, but the board view does not.

Please fix. Thank you.

**Comment by geoffturk** [comment]
@mleffler You might want to rename this issue starting with the word "Bug" in it so that it is more obvious that this is really a bug rather than a feature request.

Something like "Bug: Backlog column in Board view for Milestone not working correctly".
