### ISSUE TITLE
Datepicker fails in epic

### ISSUE THREAD

**Issue by p8** [codetree/feedback#268]
Editing a start date doesn't seem to work for an existing epic.
![image](https://user-images.githubusercontent.com/28561/43824868-b415813e-9ae2-11e8-9502-286f8b75216d.png)

Clearing it doesn't help either
![image](https://user-images.githubusercontent.com/28561/43824959-f48b327c-9ae2-11e8-9e87-0fa7834616d5.png)

**Comment by ac21** [comment]
@p8 - I think this was related to milestones and was completed with #292
