### ISSUE TITLE
add typeahead to repo picker

### ISSUE THREAD

**Issue by maxheld83** [codetree/feedback#269]
would be super nice to have a typeahead in the repo picker below

<img width="777" alt="typeahead" src="https://user-images.githubusercontent.com/5372770/45823775-bcc3ff80-bcee-11e8-97a8-5cb3f22daee0.png">

**Comment by ac21** [comment]
@maxheld83 - apologies as type ahead was implemented a couple months back.  missed this issue in our grooming.
