### ISSUE TITLE
Responsive truncation for long titles

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#27]
Really long issue titles (like the ones Airbrake generates for us) break the layout — pushing the milestone table outside the browser window. Some responsive and/or more aggressive title truncation would help with this.

![screenshot 2015-01-08 10 52 15](https://cloud.githubusercontent.com/assets/11926/5668487/ca52a1d6-9724-11e4-875f-2ae136a86170.png)

**Comment by VinSpee** [comment]
tables are annoying. Weird fix here:

http://jsfiddle.net/7CURQ/

**Comment by derrickreimer** [comment]
We should in better shape now. Tables are finicky.
