### ISSUE TITLE
Make it easy to switch between projects

### ISSUE THREAD

**Issue by haikalpribadi** [codetree/feedback#272]
Hi CodeTree team,

Right now, it's not straightforward for users to switch between projects within an organisation. Currently, the user needs to go to Organisation page, select the Organisation, a then select project.

This makes it difficult for us to work with multiple projects within an organisation, let alone viewing all of them at once. Because of this, we're making one project for all the repositories at once. Which results in one big project, which could make use of some modularisation to focus the team. However, in the near future, this is no longer suitable for us. 

We will need to at least be able to split engineering and non-engineering work (which we keep both in GitHub at the moment) into separate projects. However, if we do so, we will need to be able to switch between projects easily. Think of Slack: they allow you to switch between Workspaces easily with the left bar. Something like this (using project icons) will be very useful for us to manage multiple projects at once.

Is this possible and would you be able to add to the development roadmap?

**Comment by kareem** [comment]
If you click on the Codetree logo at the top left side of the screen it'll bring up a list of your projects.  Nt completely obvious, I know!

**Comment by haikalpribadi** [comment]
oh wow! That definitely wasn't obvious, even after using CodeTree for almost a week now. :)

The solution works for now, though. Thanks!
