### ISSUE TITLE
Updated user's name on GitHub does not sync with CodeTree

### ISSUE THREAD

**Issue by haikalpribadi** [codetree/feedback#276]
Hi CodeTree team,

When we update a name (not username) of a user on GitHub, the name of that user does not get updated on CodeTree.

For example, we have user account called @grabl. If you check on https://github.com/grabl, you can see the name is "Grabl" now. However, on CodeTree the name is still "Grakn Bot" (see below screenshot). We have tried removing the user from Organisation and Projects, and re-add the user again, but it still shows up with the old name.

![Grabl still shows as Grakn Bot](https://user-images.githubusercontent.com/567679/46289251-66717f00-c580-11e8-95ba-8421d54e975d.png)

Is there any way to sync the new name of a user, or is this a bug? Thank you!

**Comment by rstocker99** [comment]
This is a weird one. We sync the name by calling `repository_assignees` on the Github API. When I do that from the console the name they return to us is "Grakn Bot".

I'm not sure what we can do if they aren't returning the updated name.

**Comment by haikalpribadi** [comment]
Hi @rstocker99 , that's not what we see when we query the GitHub API. For example, when we use [PyGithub](https://pygithub.readthedocs.io/) which basically calls GitHub Rest API, this is what we see:
```
>>> import github as gh
>>> github_grabl = 'grabl'
>>> github_pass = <password>
>>> github_connection = gh.Github(github_grabl, github_pass)
>>> user = github_connection.get_user('grabl')
>>> user.login
'grabl'
>>> user.name
'Grabl'
>>> org = github_connection.get_organization('graknlabs')
>>> for member in org.get_members():
...     print(member.name)
...
Grabl
<other_team_members>
```

So it seems that the GitHub API is returning the correct names.

Do you have a cache somewhere that may be returning an old value?

**Comment by rstocker99** [comment]
So getting it via `respitory_assignees` was showing the old data but after forcing a sync on just the user it's corrected which I've done. You should be good now.

**Comment by haikalpribadi** [comment]
Thanks, @rstocker99! It did resolve it on our side. How do we do this _"force sync"_ on our side whenever this issue happens again?

**Comment by rstocker99** [comment]
There isn't a way on your end to force sync this. It should have synced on it's own. I've filed a bug to track. If it happens again please hit us up on support.
