### ISSUE TITLE
Ability to zoom on task board, and hide left and top panels

### ISSUE THREAD

**Issue by haikalpribadi** [codetree/feedback#277]
Hi CodeTree team,

We often use CodeTree to:
1. Show a Kanban board window open as we work, and
2. Show a Kanban board during video calls with the team.

In both cases, especially the second case, we need to zoom on just the Kanban board to have it readable on a video call screen. However, when we do so, most of the screen is filled up by the left and top panel. See the screenshot below.

![CodeTree Kanban board view](https://user-images.githubusercontent.com/567679/46289573-602fd280-c581-11e8-90f1-615bd9bceea8.png)

It would be very valuable if we can zoom on just the kanban board by hiding the left and top panel, allowing the issues to take up all the screen. Is this a possible feature to add to (or already in) the roadmap?

**Comment by rstocker99** [comment]
So basically a distraction free mode where the left nav and filter bar are hidden?

BTW, if you haven't noticed already you can toggle the Open and/or Closed columns via the buttons under the columns. That can be useful to create a bit more room in some cases.

**Comment by haikalpribadi** [comment]
Hi @rstocker99, we actually need the `open` and `closed` columns. 

> So basically a distraction free mode where the left nav and filter bar are hidden?

Yes, but we also need the columns to stretch when there's more space, otherwise reading the cards are just as hard. Although, this is already described in issue #275.

**Comment by schwern** [comment]
I also would like this. It both means less distractions and also more space to see and manipulate more board.

Perhaps a sidebar that collapses to icons and expands on hover.

The header could be made very thin. The search bar could be moved into the sidebar. Or it could be moved to the left of "Showing task board..." and expand on focus.

**Comment by ac21** [comment]
@schwern - we just released #335 (full screen mode) by using cmd/ctrl + shift + f  does that meet your needs?
