### ISSUE TITLE
Ability to organize task board with GitHub labels

### ISSUE THREAD

**Issue by ajwaxman** [codetree/feedback#28]
I love the new task board :heart: 

In addition to organizing issues by Backlog, To Do, In Progress, and Done, it'd be great to be able to customize the columns. One way to do this would be to have them associated with GitHub labels. For example, in the case below a `Backlog` label would be applied to the issues in the left hand column, and when moved to the To Do column the `Backlog` label would be removed and a `To Do` label would be added.

![](http://cl.ly/ZDfL/Image%202015-01-08%20at%204.05.24%20PM.png)

**Comment by derrickreimer** [comment]
Thanks Adam! Custom stages for task boards is in the works. Regarding the `Backlog` and `To Do` columns, I am trying to rely on the "natural state" of issues as much as possible to reduce label noise (and stick to convention over configuration). But I'm definitely open to hearing use cases where this falls down.

**Comment by ajwaxman** [comment]
Yeah one downside to the this approach is definitely label noise. I also appreciate the desire to stick to convention over configuration - definitely a good point. 

However, from briefly using this approach with waffle.io I found it a nice way to use a 3rd party tool and also be able to see the activity/state of a given issue on GitHub as well.

**Comment by VinSpee** [comment]
I love sticking to the "natural state" as much as possible.

**Comment by wanderingmatt** [comment]
:+1: for relying on natural state here. While I could see the case for having additional label-based boards (allowing you to define your own states), I don't feel like I need a labels on Backlog or Todo issues to understand their state over on Github.

**Comment by ajwaxman** [comment]
@djreimer I overlooked the part of your reply that said custom stages for task boards is in the works. Very exciting! How will custom stages be created and modified? Will it be a codetree only state or will it be compatible with the Github Issues interface as well?

> I don't feel like I need a labels on Backlog or Todo issues to understand their state over on Github

Agreed, I don't think this should be a requirement (or even the default). However, I do think that some teams will find it helpful for various states to be easily filterable and labeled in GH

**Comment by derrickreimer** [comment]
@awaxman11 custom stages will be label-based, similar to the `In Progress` column. Actually, the `In Progress` column will be customizable as well.

**Comment by ajwaxman** [comment]
Awesome!

**Comment by dblandin** [comment]
This feature [shipped recently](http://blog.codetree.com/articles/custom-stages.html). Our team has setup custom `review` and `qa` stages. Works wonderfully. Time to close this issue?

**Comment by derrickreimer** [comment]
Good catch @dblandin!

**Comment by ajwaxman** [comment]
Super excited to try this out!!

**Comment by derrickreimer** [comment]
Woot!
