### ISSUE TITLE
Allow visibility toggle for custom stages

### ISSUE THREAD

**Issue by svenyonson** [codetree/feedback#286]
Currently, you can show/hide the default triaged and done stages. In a given project, not everyone needs to see all of the stages. And sometimes there are enough stages to make it difficult to fit on the screen. Please add the ability for a user to toggle the visibility of custom stages.

## Proposed Solution
1.  Add a new visual paradigm, wherein each column header is a collapse icon.
2. when clicking the collapse icon, the column should shrink to just ~25-30px, just enough for the column/stage name to be listed vertically and a count of items in the column.
3.  When a column is collapsed, an expand icon should be available
4. When the expand icon is opened, the width returns to its fair-share distribution

see codetree/codetree#2137 for visual example

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21307193208
+1

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/search/conversations/21246845663
+1

**Comment by ac21** [comment]
@sachinkum123 updated the proposed solution to a different visual paradigm

**Comment by ac21** [comment]
@sachinkum123 
https://fontawesome.com/v4.7.0/icon/compress
https://fontawesome.com/v4.7.0/icon/expand
example html:
```html
<i class="fa fa-expand ng-scope" aria-hidden="true"></i>
```
example css . (to rotate the image 45 degrees so it appears like it is horizontal:
```css
.column-toggle i {
    font-size: 15px;
    transform: rotate(45deg);
}
```
