### ISSUE TITLE
Move cards/issues from the To-Do stage to In Progress (or other custom stage) on creation of a branch in a fork of the default repo

### ISSUE THREAD

**Issue by misskniss** [codetree/feedback#290]
When using the "Fork and Branch Workflow" for git hub, my team and I need a way for the issues in the _To-Do_ stage to move to the _In Progress_ stage when we push a branch *to our own forks* of the default repo. 

Without this, we have no real way to say this issue is 'in progress' unless someone manually moves the card in the Code Tree UI. Because we do not create our feature branches directly off the company repo, there is no way to tell that any work has begun on an issue until it is already in PR and in that case, the issue is _Ready for Review_ as opposed to _In Progress_.

With a feature that automatically does this when we push a branch to our fork, we do not have to context switch from our command line to the web interface to indicate that we have started work on an issue.

**Comment by ac21** [comment]
needs https://github.com/codetree/codetree/issues/1994
