### ISSUE TITLE
Ability to sort and/or filter issues by creation date and last updated date

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#297]
## Background 
A common use case is looking at recently submitted or updated tickets, however its hard to find them in codetree as their no ability to sort.  Currently, sorting is always based on the manually sorted view

## solution
* add the ability to sort by `created_at` and `updated_at`
* allow sorting overall, within filters, and sorting within milestones
* add the ability to filter by `created_at` and `updated_at`

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/20552070944

**Comment by bfelbo** [comment]
It would be great if this could be sorted by anything that you can do as filters. For instance, we'd love to sort by a label.

**Comment by sanjaypojo** [comment]
+1 for sorting by labels. This could even be a global setting. For example, I'd like `wont-fix` to always go to the bottom, and `today` to always be at the top etc.

**Comment by ac21** [comment]
+1 - @maxthoursie
