### ISSUE TITLE
Ownership transfer doesn't remove payment alert

### ISSUE THREAD

**Issue by VinSpee** [codetree/feedback#30]
## Current

When ownership is (manually) transferred, the previous owner will still see the "Update your payment information before your trial expires." box, even if a payment method has been added.
## Expected

If I'm not an owner, I shouldn't know anything about payments.
## Screencap

![screen shot 2015-01-09 at 7 41 41 pm](https://cloud.githubusercontent.com/assets/582828/5689647/8f57bfda-9837-11e4-8e2f-74439ce2f125.png)
![screen shot 2015-01-09 at 7 40 21 pm](https://cloud.githubusercontent.com/assets/582828/5689648/8f5885fa-9837-11e4-9096-981701a4afd0.png)

**Comment by derrickreimer** [comment]
Should be fixed now. Looks like I missed updating one attribute when manually transferring the organization. Will be sure to cover this when building transfers :)
