### ISSUE TITLE
Enable showing epic in list view 

### ISSUE THREAD

**Issue by orgalaf** [codetree/feedback#300]
We need the epic visible with each issue in list view. We use it for sprint planning and are currently resorting to labels as a workaround. 
Thanks

**Comment by ac21** [comment]
@orgalaf - do you mind providing a bit more explanation?  the default view shows the milestones (see right hand side of image below), so I'm a bit confused on the request
![Screen Shot 2019-01-27 at 11.07.08 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/c147200c-fcf2-4505-9120-d723636e6715/Screen+Shot+2019-01-27+at+11.07.08+PM.png)

**Comment by orgalaf** [comment]
Sorry, it's early morning here. I meant epic...

**Comment by orgalaf** [comment]
Is there an eta on this?

**Comment by ac21** [comment]
@orgalof - i would have liked to get to this in Q1, however it’s not making the prioritization cut, at the moment.  I think we can push this through in Q2.
