### ISSUE TITLE
Show repo names in table view

### ISSUE THREAD

**Issue by sanjaypojo** [codetree/feedback#305]
No easy way to view which repo an issue corresponds to (except hovering over the issue)

**Comment by ac21** [comment]
@sanjaypojo - apologies this was overlooked.  This is available as a setting.    Closing...
![Screen Shot 2019-11-01 at 10 09 12 PM](https://user-images.githubusercontent.com/6155532/68065229-4b79bd00-fcf4-11e9-80ee-07b2f064c37b.png)
