### ISSUE TITLE
Intermittently the issues in the untriaged bucket goes empty

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#307]
## Background 
From time to time, the issues in the untriaged bucket disappear:
![screenshot from 2019-02-19 13-52-52](https://user-images.githubusercontent.com/6155532/53067432-c5855100-3499-11e9-8b55-1d96e32a5197.png)

## Repro
< not able to repo yet>

**Comment by maxthoursie** [comment]
I belive it's the same issue as https://github.com/codetree/feedback/issues/282 . The problem went away when I entered my card and the "Update you payment" popup went away.

**Comment by ac21** [comment]
closing the issue as it is no longer occuring
