### ISSUE TITLE
Creating + breaking dependencies through Codetree

### ISSUE THREAD

**Issue by derrickreimer** [codetree/feedback#31]
/cc @andacturkmen @lightcap

**Comment by lightcap** [comment]
I love that the closed deps disappear, btw. But there should be a way to "unhide" them maybe?

**Comment by VinSpee** [comment]
how do i set up dep issues?

**Comment by derrickreimer** [comment]
@lightcap not a bad idea

@VinSpee you can add a dependency to another issue by dropping a comment like "needs #31". Codetree automatically parses these references out. We accept "need", "needs", "needed", "require", "requires", "required" (similar to GitHub's "fixes" convention for pull requests).

**Comment by JohnLemberger** [comment]
How do you create cross-repo dependencies?  I tried `needs http://github.com/.../issues/####` but it hasn't linked.

**Comment by derrickreimer** [comment]
Hi @JohnLemberger! The syntax is like this: `needs codetree/feedback#31`. GitHub will recognize the reference in this format too and include it in the activity feed for the issue: https://help.github.com/articles/writing-on-github/#references

**Comment by aseemk** [comment]
Would you guys consider automatically picking up issues linked in Markdown task lists? E.g.:
- [ ] #1234 Foo bar
- [ ] [#1234] Foo bar
- [ ] Issue #1234: Foo bar
- [ ] Foo bar #1234
- [ ] Foo bar (details in issue #1234)

That's the convention we've been using for a long time across many of our issues, and it's one that we've seen others use too. (E.g. [see here](http://www.ianbicking.org/blog/2014/03/use-github-issues-to-organize-a-project.html); cmd+F for "master issue".)

**Comment by derrickreimer** [comment]
@aseemk that's an interesting idea. These wouldn't necessarily be dependencies though, right? I could see listing these relationships more generically under the parent. E.g. this is how dependencies are listed now:

![dependencies](https://cloud.githubusercontent.com/assets/341387/6056332/0144fee6-acc4-11e4-983c-bca267f0f408.png)

Perhaps other referenced issues could appear as "references [Issue title]". How does that sound?

**Comment by aseemk** [comment]
I don't think listing referenced issues is a bad idea, but to be clear, the task list use case is indeed for dependencies. The referenced issues contain more detail for tasks of the master issue; the master issue isn't done until all its tasks, and thus those referenced issues, are done.

**Comment by aseemk** [comment]
Random minor thought: the word "mentions" is nicer and shorter than "references", if you do add referenced issues to the UI. =)

**Comment by derrickreimer** [comment]
> Random minor thought: the word "mentions" is nicer and shorter than "references", if you do add referenced issues to the UI. =)

:+1: 

> I don't think listing referenced issues is a bad idea, but to be clear, the task list use case is indeed for dependencies.

Just thinking of edge cases here, I'm fairly sure I've referenced another issue in a task list (I'm a heavy task list user myself) without implying a dependency. Assuming that all issues referenced in task lists are dependencies might be dangerous.

Would it mess with your flow too much to use one of the accepted reference keywords (need, needs, needed, require, requires, required) in front of the issue number?

**Comment by aseemk** [comment]
Yeah fair enough, I'm sure we've done that too. =)

It wouldn't mess with our workflow; it's just friction...

**Comment by derrickreimer** [comment]
I'll keep noodling this one. Perhaps a simple convention like this will reduce friction:

---

Needs:
- [ ] #12345
- [ ] #23456

**Comment by kareem** [comment]
Just launched breaking dependencies:

https://changelog.codetree.com/break-dependencies-25746

Moving @aseemk's [comment](https://github.com/codetree/feedback/issues/31#issuecomment-73003452) about parsing multiple dependencies out of a list to a new issue.
