### ISSUE TITLE
Allow Ctrl+Enter to submit new issue

### ISSUE THREAD

**Issue by alexykot** [codetree/feedback#311]
Would be great to be able to submit the New Issue form from keyboard with standard shortcut `Ctrl`+`Enter`/`Cmd`+`Enter`. When editing new issue title or description you can submit by `Tab`bing to the button, but would make sense to also do that via `Ctrl`+`Enter`/`Cmd`+`Enter`.

**Comment by ac21** [comment]
@sachinkum123 - It looks like you didn't update the `Keyboard Shortcuts` with the new command:

Can you address this:
![Screen Shot 2019-04-02 at 9.31.08 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/b9a7ecf9-fbab-448b-a46a-4a62f0ab1bb8/Screen+Shot+2019-04-02+at+9.31.08+AM.png)
