### ISSUE TITLE
Link to epic fails if epic name has commas

### ISSUE THREAD

**Issue by alexykot** [codetree/feedback#312]
If I add a comma into Epic name - the link to issues of this epic breaks and list shows "no issues". See attached pics
![screenshot from 2019-03-06 12-03-55](https://user-images.githubusercontent.com/1840160/53880119-1b183c80-4008-11e9-8437-0cde67be8c56.png)
![screenshot from 2019-03-06 12-04-50](https://user-images.githubusercontent.com/1840160/53880120-1bb0d300-4008-11e9-8965-729a48886226.png)

.

**Comment by ac21** [comment]
@sachinkum123 - can you attempt to reproduce?
