### ISSUE TITLE
Burndown is showing incorrect data intermittently

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#315]
## Issue
For some users, the burndown chart is displaying incorrect data; specifically, the counts start at 0 and goes negative.  
![Alle_-_Burndowns](https://user-images.githubusercontent.com/6155532/54833717-a6dacb80-4c8c-11e9-8174-d986b84a2632.png)

## repro
unknown at this point

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21123162566
+1

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/search/conversations/21203143998
+1

**Comment by shlomi-nx** [comment]
We are evaluating codetree and experience this exact issue. Please let me know if there is any info I could provide for this to get solved.

**Comment by ac21** [comment]
@shlomi-nx - It's in this sprint, so by next Fri 4/12

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21512166215
+1

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21541758090
+1
