### ISSUE TITLE
when viewing issues, make the "assigned to" a selectable too

### ISSUE THREAD

**Issue by Pomax** [codetree/feedback#32]
Right now the issue filter system offers a few manipulable options, as shown here:

![screenshot 17](https://cloud.githubusercontent.com/assets/177243/5709188/8bc54592-9a4c-11e4-9ed6-3cb511d73f58.png)

However, it's (critically, I'd say) important that the "assigned to" part is a multi-filter, too, so that we can search for things like

"Showing [_open issues_] [_assigned to_ or _@-mentioning_] [_Pomax_] labeled with [_p1_]"

**Comment by derrickreimer** [comment]
This makes sense. Is the most common pairing (assigned to OR mentioned) for you?

**Comment by Pomax** [comment]
it's certainly the one I run into most often, since github doesn't do multiple assigning (so if the task owner's assigned, and I'm cc'd as a dev, but it's a p1 ticket, I still really want to be able to find that =D)

**Comment by derrickreimer** [comment]
Added an "Interacted" filter which should cover this!
