### ISSUE TITLE
Easy way to link issues to an epic

### ISSUE THREAD

**Issue by phagunbaya** [codetree/feedback#326]
Currently to link an issue to epic, you need to search for it and then add it which is not a cool way. It would be great if codetree can scan the issue description and extract the issue list from there.
Example:
Adding "Parent of #123" in the description should link #123 to the epic issue.

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21582862660
+1
