### ISSUE TITLE
Adding new issue should come up to the top

### ISSUE THREAD

**Issue by phagunbaya** [codetree/feedback#329]
When adding new issue, it gets to the bottom of the list. Best thing would be to have that issue on the top of the column. Also, when moving issues across column, they should get added to the top unless dropped at a particular place.

**Comment by ac21** [comment]
@phagunbaya - did you see the option when creating an issue to set where it will appear in the order (top or bottom)?

**Comment by phagunbaya** [comment]
Found it. This is resolved then.
