### ISSUE TITLE
Allow for attachments to issues

### ISSUE THREAD

**Issue by VinSpee** [codetree/feedback#33]
We've invited our customer support team to our github org and instructed them on how to create issues. We'd love for them to be able to use the CodeTree UI, but in order to do so, they need to be able to attach screenshots and other assets (eps, ai, svg, pdf).

**Comment by derrickreimer** [comment]
@VinSpee this is in the queue. Will keep you informed.

**Comment by wanderingmatt** [comment]
:+1:

**Comment by jeanfw** [comment]
:+1:

**Comment by Too-Funky** [comment]
:+1: Yeah it would be awesome if you could paste img, gif etc direct into the issue box (like on regular github issues)

**Comment by myamakerspace** [comment]
How's this going. I don't want to have to go back to plain github, I love how codetree displays.

**Comment by kareem** [comment]
Hi all, we just launched file attachments in Codetree.  Would love any feedback you've got.  Thx.
