### ISSUE TITLE
Improve Assignee functionality

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#332]
## Background
currently, assignee functionality is a little clunky as the sorting of assignees appears to be random (or at least not prioritized in a logical way

## Solution
1. adjust the sort order of assignees to be:  already assigned people (alphabetized), own account, everyone (alphabetized) 
2. add a "clear assignees" button at the top when assignees exist
3. add a gear icon next to Assignees as it's more intuitive (add one next to Epic as well)

### AC1: gear icon
Given I am a user
When I have opened up an issue
Then I should see a gear icon to the right of Assignees
and clicking the gear icon should show the list of Assignees

### AC2: no one assigned
Given I am a user
And the target issue has no users assigned
When I have opened up the issue
Then I should see a message below assignees that says: `No one - assign yourself` with `assign yourself' being a hyperlink when clicked that assigns myself to the ticket

### AC3: assigned users
Given I am a user
And I have opened an issue with at least one assigned user
When I click on the gear icon (or the assigned user)
Then I should see the user selection screen
And the first link in the user selection screen should be `clear assignees' that when clicked clears all assignees
And the list of users should be sorted: assignees (a->z), own account, everyone else (a->z)

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21454522334
+1

**Comment by ac21** [comment]
Also, take a look at #337 as showing real names and searching by real names would also improve usability

**Comment by sachinkum123** [comment]
@ac21 Could you please share the screenshot where I need to make changes and add the acceptance criteria?

**Comment by ac21** [comment]
![Screen Shot 2019-05-16 at 10.52.32 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/85a9382b-5196-4065-bff5-b16b9eb1cbcf/Screen+Shot+2019-05-16+at+10.52.32+PM.png)

Top circle is where the Gear Icon goes
Bottom circle is where the clear assignees goes

**Comment by sachinkum123** [comment]
![DEV  Sachin Kumar   Issues (1)](https://user-images.githubusercontent.com/48723518/58187904-548e4900-7cd5-11e9-821f-9dc63da19e20.png)
![DEV  Sachin Kumar   Issues](https://user-images.githubusercontent.com/48723518/58187905-548e4900-7cd5-11e9-973d-54a76c521899.png)
