### ISSUE TITLE
collapsed kanban columns too prominent

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#333]
## Background
Recently a new feature was released to collapse kanban columns.  However, some feedback has bubbled up saying that the collapsed columns are two prominent given the dark grey contrast

## Solution
change the color scheme to make the column less prominent and fade more into the background

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21589206291
+1

**Comment by sachinkum123** [comment]
Does this look better?
![Screenshot from 2019-04-17 16-43-08.png](https://codetreeusercontent.s3.amazonaws.com/uploads/533c940d-10a9-46cb-9686-906e96d76bbd/Screenshot+from+2019-04-17+16-43-08.png)

**Comment by ac21** [comment]
let's go with a white background, light grey label

**Comment by sachinkum123** [comment]
It will look like this,
I also changed the color of unfold icon to light gray 

![final-board.png](https://codetreeusercontent.s3.amazonaws.com/uploads/cfb8c8da-b43a-4139-b808-3ada474fa186/final-board.png)

**Comment by ac21** [comment]
looks great!
