### ISSUE TITLE
Provide a full-screen mode when viewing the kanban board

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#335]
## Background
Some users are often trying to see as many of their issues and columns as possible when looking at the kanban board.  Additionally, users may want to be able to view their kanban board as a dashboard (e.g., a projected or conference room screen).  

## Solution
Provide a full-screen mode that:
* hides the left hand menu bar
* hides the top search bar, codetree logo, and user name/menu
* hides the footer (export to CSV/JSON and Settings)
* enabled/disabled via keyboard shortcut

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21676368242
+1

**Comment by sachinkum123** [comment]
![DEV  test   Board](https://user-images.githubusercontent.com/48723518/57781071-0f9f6b00-7747-11e9-9c8c-c95c1a80f088.png)

**Comment by ac21** [comment]
Resolves #277
