### ISSUE TITLE
Show PRs with reviewers instead of assignees

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#336]
## Background
The typical process for PR's is to go through a code review and GitHub has workflow built out to support the review process.  However, it's unclear from Codetree what the current status of the Code Review is from the taskboard or issues list (or even opening the review)

## Solution
update the taskboard cards and issues list views for PRs to show Reviewers instead of Assignees.  In addition color code a status around the reviewer icon and add hover information for the PR/icons to see the current status:  for instance, red for requested change, green for approved, yellow for pending.

### Example
<img width="241" alt="pr_status" src="https://user-images.githubusercontent.com/6155532/56627203-6ca57680-660a-11e9-8174-773caa6f0fab.png">

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21745187449
+1

**Comment by ac21** [comment]
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21978931640
+1

**Comment by sachinkum123** [comment]
NOTE: Show reviewers and assignees both on PR'S
