### ISSUE TITLE
When viewing users, show their real name next to their aliases

### ISSUE THREAD

**Issue by shlomi-nx** [codetree/feedback#337]
Some of our external users have funny github handles that have nothing to do with their names. It makes it difficult to remember each person's favorite childhood cartoon star :)

It would be much easier if we could see and search by their actual name as well as their handle when we want to assign them to an issue or filter their issues.

**Comment by ac21** [comment]
@shlomi-nx - makes sense.  I'll have our team review this and see what we can do as we are working on some assignee improvements already

**Comment by sachinkum123** [comment]
![assignees-name.png](https://codetreeusercontent.s3.amazonaws.com/uploads/42d983f5-b6cc-4965-bcc2-4fd080aff8f6/assignees-name.png)
