### ISSUE TITLE
Allow changing the stage from the list or edit view.

### ISSUE THREAD

**Issue by schwern** [codetree/feedback#342]
When looking at the List View of issues, I would like to be able to change the stage of the issues quickly without having to switch to the Board View. Making "Stage" a dropdown would work.

This would also be useful in the Edit View. Show the stage (it's currently not shown) as a dropdown. Currently I'm manually changing the labels.

**Comment by ac21** [comment]
@schwern - this resolved a little while back.  apologies for not closing and notifying sooner
