### ISSUE TITLE
Assign issue to branch owner as part of branch creation workflow

### ISSUE THREAD

**Issue by sfitts** [codetree/feedback#346]
## Background / Customer Feedback

When an issue is moved to a stage based on branch creation it would also be nice to set the assignee of the issue to be the branch owner.  We're coming from Waffle and this was one of the features that it had (makes it clear, not just that the issue is being worked on, but who is working on it).

Might be related to #114 (though that seems to be related to a fixed assignment based on stage and this would be a variable one).

## Solution
When a branch is created and an issue is moved to a custom stage, set the assignee to the acting user (from the branching action) if no assignee exists

### AC1: Assign branching user to unassigned issue
Given I am a User
And a given issue has no assignee
When I create a branch for the given issue (matching the workflow rules) and push it
Then the branch should move to the designated custom stage
and I should be assigned to the issue

**Comment by ac21** [comment]
@sfitts -  this seems like a great feature.  In my mind, this only applies if the assignee is empty on branch creation.  Do you agree?  (FYI, pulling this in for scoping)

**Comment by sfitts** [comment]
@ac21 that seems reasonable.  Thanks for looking at this, it is probably our top missing feature right now.

**Comment by ac21** [comment]
Links to customer requests (internal use only; end-users can not open)
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/21968804970

**Comment by ac21** [comment]
completed and deployed
