### ISSUE TITLE
Quick set assigning without full issue modal

### ISSUE THREAD

**Issue by sfitts** [codetree/feedback#347]
It would be nice to be able to set/change the assignee of an issue by clicking on the icon and without having to bring up the entire "edit issue" modal.

If having the entire assignee droplist is too much in this context, perhaps a simple "assign to me" button or menu item (this is exacerbated by #346 -- if that were implemented I might never change the assignee manually, except in cases where the full dialog isn't that annoying).

**Comment by ac21** [comment]
@sfitts - agreed!  adding to Q4 roadmap

**Comment by ac21** [comment]
needs codetree/codetree#2959

**Comment by ac21** [comment]
shipped
