### ISSUE TITLE
I'd like to be able to open a new epic anywhere I can open a new issue.

### ISSUE THREAD

**Issue by schwern** [codetree/feedback#351]
When I'm entering and organizing a bunch of new tasks I need to create both issues (stories) and epics. The New Issue button is ubiquitous, but I only seem to be able to create a new epic by going to the Epic board. This adds extra steps to the process of entering and organizing.

Perhaps the New Issue button could have a little drop down to select other things to create, much like a Github PR. If you click on the button it makes a new issue. If you hit the little triangle you get more options.

<img width="331" alt="Screen Shot 2019-05-22 at 13 52 42" src="https://user-images.githubusercontent.com/25888/58208137-fe9bb000-7c98-11e9-9701-c83e8f9afad6.png">

Or perhaps when creating a new issue there would be a way to create a new epic and assign the issue to it.

**Comment by ac21** [comment]
needs #2529
