### ISSUE TITLE
Issue list layout broken in Safari

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#36]
![issues codetree](https://cloud.githubusercontent.com/assets/4361/5767836/48209e38-9cc0-11e4-8c0a-f0076e7cd76b.png)

**Comment by derrickreimer** [comment]
Yikes, sorry Shane. It's definitely not supposed to look like that. Are you by chance using Safari? We are working on a fix now for layout issues in that browser.

**Comment by veganstraightedge** [comment]
I am using Safari. Latest Safari. Latest OS X. 
Anything else you need from me/my environment?

**Comment by derrickreimer** [comment]
No thanks, that'll do. Expect a fix soon.

**Comment by veganstraightedge** [comment]
Thanks!

**Comment by derrickreimer** [comment]
Should be fixed now. Let me know if you run into any other issues!

**Comment by veganstraightedge** [comment]
Looks good to me. Thanks!

**Comment by derrickreimer** [comment]
:metal:
