### ISSUE TITLE
Enable fuzzy searching rather than strict matching

### ISSUE THREAD

**Issue by ac21** [codetree/feedback#362]
## Situation
Currently when searching, only exact word matches are returned which makes it harder to find issues than it should be.

## Solution
Enable fuzzy searching to find similar and related words (e.g, issue, issuing, issues, issued, etc.). 

Our primary search results are in Elastic Search rather than postgres.   As such, we need to update our Elastic Search query to pull via fuzzy search instead of exact match:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html

**Comment by ac21** [comment]
For internal use only:
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/22834029676

**Comment by ac21** [comment]
For internal use only:
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/2848986/conversations/22834029676
https://app.intercom.io/a/apps/he4q7g1x/inbox/inbox/all/conversations/23087908297

**Comment by sanjaypojo** [comment]
Really need this, struggling to search for items because we often write issues with code in them and figuring out whether there's a space or an opening quote etc. is really hard. We end up creating a lot of duplicate issues because we never find the original issue when we search for it.

**Comment by sachinkum123** [comment]
Update the indexing strategy and remove unnecessary fields 
and add number field

**Comment by ac21** [comment]
Migration steps:
1. verify existing indices:  `curl http://localhost:9200/remote_issues?pretty=true`
2. reindex issues: `bundle exec rake migrations:reindex_search`
3. verify new indices: `curl http://localhost:9200/remote_issues?pretty=true`

**Comment by ac21** [comment]
@sachinkum123 - I can't explain all your environment issues, however, `migrations:reindex_search` previously was creating field index strategies based on a "best-guess" approach that isn't working for our use case which is to supply a common text string and have it search, by test the number, title, and body fields.  To fix this, `migrations:reindex_search` needs to be modified to define the field index straegies explicitely, in particular that we want the number column to be stored as text (not a numeric value).  

See the [commit 1617b85a](https://github.com/codetree/codetree/pull/2398/commits/1617b85aa0a8d305f4d0df70ec61435244a7cef8#diff-ed9bd0cba090159f87a4273f763021ebR144)
