### ISSUE TITLE
Milestone names get stuck in cache when updated

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#37]
We had a milestone named: "v1.4 Feed".
We changed it to "Public Feed".

New issues created in this milestone show the correct name ("Public Feed").
Issues created in this milestone before the name change retain the old/wrong name ("v1.4 Feed").

**Comment by veganstraightedge** [comment]
![screen shot 2015-01-16 at 11 01 53 am](https://cloud.githubusercontent.com/assets/4361/5782465/dfad53fe-9d6f-11e4-8ec9-4054fc6575f3.png)

**Comment by derrickreimer** [comment]
Thanks, I think is a case of cache invalidation not happening when it should. I'll investigate.

**Comment by veganstraightedge** [comment]
One of the two hard problems of computer science. ;) 

http://tantek.com/2010/085/t2/hard-problems-computer-science

**Comment by derrickreimer** [comment]
Should be fixed now
