### ISSUE TITLE
"Priority" setting on New Issue panel no longer sticky

### ISSUE THREAD

**Issue by sfitts** [codetree/feedback#373]
We noticed that recently the "priority" field (Move to Top/Bottom) in the New Issues panel is no longer sticky.  So if we want to default to adding issues at the top (which we do), we now have to reset that option for every issue creation.  Given that the other fields in that panel are sticky, this choice seems a bit odd (and for us it is somewhat annoying).  I can see arguments for why none of the fields should be sticky, but if you go that route then you'd likely need an alternative way to control the defaults.  Anyway, if possible, we'd like the previous behavior restored.

**Comment by ac21** [comment]
@sfitts - this issue should now be solved be restoring the previous behavior.
