### ISSUE TITLE
Add ability to manually refresh issues

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#39]
When my issues/milestones get out of sync with the GitHub Issues Truthiness™, I'd like to be able to force Codetree to re-sync **now** as opposed to **sometime**. 

Or at the least, so visibility into that re-syncing schedule / progress would be swell.

**Comment by aseemk** [comment]
+1

**Comment by jasny** [comment]
I think this has been implemented.. right?

**Comment by derrickreimer** [comment]
@jasny not yet. The "Sync My GitHub Data" triggers a manual refresh of the currently logged in user's data (most importantly, their repository permissions).

**Comment by jwpeddle** [comment]
I just got burned by this while trying to demo the needs/blocking functionality. I thought I was using the wrong word, but I guess the ticket just hasn't updated yet. I looked for a way to force sync, but found no such option.

**Comment by derrickreimer** [comment]
Bummer, sorry about that @jwpeddle

**Comment by peritpatrio** [comment]
+1

**Comment by mrenvoize** [comment]
+1.. or just stay in sync ;)

**Comment by derrickreimer** [comment]
@peritpatrio @mrenvoize thanks gents.

@mrenvoize - we do our best with what GitHub sends us in webhooks :). I've been lobbying them for quite some time to send webhooks when milestones are added to issues and when titles/bodies are updated.

**Comment by mrenvoize** [comment]
It's a shame they don't support this then (I'd be interested to see how some other tools work.. I'm sure I didn't have this issue when using waffle.io).

Having a manual refresh would be a good interim measure though. Currently I can't actually tell if the big selling point for us actually works at all as the sync is so slow. (the 'needs' dependency handling).

**Comment by jorgemanrubia** [comment]
This would be very handy indeed. I am evaluating codetree. I organized a few issues using github UI and assigned them a milestone. After like 20 minutes Codetree is still outdated. Also you don't have a clue of when/if the data is going to sync at all.

**Comment by kareem** [comment]
@jorgemanrubia thanks for the feedback.  We agreed that this experience isn't as great as it could be / needs to be.  We have some ideas about how to improve milestone syncing.  Sit tight! :)

**Comment by mrenvoize** [comment]
We have given up on this service in afraid,  I realise github are making it hard without offering all the webhooks you require,  but other similar services don't appear to have such prominent issues.  We're using https://overv.io a fair bit now as an alternative. And have been happy with its sync so far.

**Comment by derrickreimer** [comment]
FWIW, GitHub has closed most of the webhook gaps that existed for a long time. I rarely see my Codetree project out of sync with GitHub nowadays.

**Comment by kareem** [comment]
@mrenvoize sorry you've left us.  we're actively working on sync issues right now and hope to have them addressed soon.

**Comment by kareem** [comment]
We've implemented a solution to speed up syncing.  If you still notice syncing issues by all means comment in this ticket or open up a new one, but things should be a lot snappier sync-wise now.
