### ISSUE TITLE
Edit issues from Codetree

### ISSUE THREAD

**Issue by dphaener** [codetree/feedback#4]
Would be nice to see the following:
- Ability to close the issue from the app
- Ability to view the body text of the issue in the app

**Comment by derrickreimer** [comment]
Thanks. This feature is next up to ship, currently in progress.

**Comment by aseemk** [comment]
Does this include creating new issues? If so, major +1. =)

(Our use case: during planning meetings, we will frequently want to see the big picture, but quickly and rapidly add tasks also. Same with e.g. triaging feedback from bug bashes.)

**Comment by aseemk** [comment]
(Let me know if I should create a separate issue for that, if this doesn't cover that.)

**Comment by derrickreimer** [comment]
> Does this include creating new issues? If so, major +1. =)

Actually, new issue creation is there now.

![new-issue](https://cloud.githubusercontent.com/assets/341387/4989533/dbfa2a04-692e-11e4-8cd9-8a1e6785bd21.jpg)

**Comment by derrickreimer** [comment]
> Ability to close the issue from the app

Issues can now be closed by clicking the icon next to the sort handle. In addition, labels can be added/removed by clicking the label icon, and the assignee and milestone can be updated by click in their respective columns.

> Ability to view the body text of the issue in the app

I might add this eventually, but I'm trying to avoid duplicating too much UI that GitHub already executes really well. Going to close this one out for now.
