### ISSUE TITLE
Add "Repository" column to issue list

### ISSUE THREAD

**Issue by rinopo** [codetree/feedback#40]
Hi,
I'd love it if you could add a "Repository" column to the issue list, so that one can see from which repo an issue is coming from at a glance.

![issues codetree](https://cloud.githubusercontent.com/assets/45791/5796043/1dedc842-9fe1-11e4-9988-3fe9e495bebe.png)

Maybe you could also make the visibility of certain columns optional for people who don't need to see them. (This could be related to #7 )

**Comment by derrickreimer** [comment]
:+1: we are working on freeing up some space in the list view to accommodate more data. For now, you can hover over the issue number to see the repository name in a tooltip (although I know that doesn't help you see it at a glance).

**Comment by rinopo** [comment]
Thanks for the reply and great to hear that the improvements are coming!

BTW, I've also noticed that in the case of the screenshot posted above, the "Assignee" column is also redundant, since the table itself is divided by the tasks' assignees.

**Comment by rinopo** [comment]
For the meantime, I've made a quick and dirty Stylish user style to always show the repository names:
https://userstyles.org/styles/109618/codetree-repository-label

**Comment by derrickreimer** [comment]
Alrighty, here it is. In Settings:

![show-repo-name-option](https://cloud.githubusercontent.com/assets/341387/6115661/1e16aa7e-b05c-11e4-9c61-a204123ae079.png)

When checked, you'll see the repo name here:

![repo-name-in-list](https://cloud.githubusercontent.com/assets/341387/6115673/28b10934-b05c-11e4-9496-18633784f478.png)

Enjoy!

**Comment by rinopo** [comment]
Great! Thanks a lot :smiley:
