### ISSUE TITLE
Ability to add private repo w/ collaborator access

### ISSUE THREAD

**Issue by rinopo** [codetree/feedback#41]
There's a repo that I have on my list of repositories on GitHub but cannot add to a Codetree project.
It's a repo that I've been invited to with a [collaborator access](https://help.github.com/articles/permission-levels-for-a-user-account-repository/) permission.

Could you make this kind of repository available in Codetree too?

![repositories](https://cloud.githubusercontent.com/assets/45791/5796164/8f8bf1fa-9fe5-11e4-89a1-e8f3c21f7af6.png)

![default](https://cloud.githubusercontent.com/assets/45791/5796201/4c48d9fc-9fe6-11e4-9534-c18a15d0627a.png)

**Comment by derrickreimer** [comment]
Great question! The reason we require owner/admin rights is because Codetree relies heavily on webhooks to keep data in sync with GitHub, but collaborators are not allowed to install webhooks. Would it be possible to have the owner of the repo set up the project?

**Comment by rinopo** [comment]
Thanks for the explanation!

> Would it be possible to have the owner of the repo set up the project?

Yeah, since that seems to be the only solution, I'd ask them to do so.
Maybe you can close this issue.

**Comment by derrickreimer** [comment]
Sounds good. Let me know if you have further questions.
