### ISSUE TITLE
Clarify the split between issues & PRs on milestone completion status

### ISSUE THREAD

**Issue by lightcap** [codetree/feedback#42]
I have a milestone that shows as 97% complete with one issue open, but I don't see any open issues in the milestone.

Clicking on the milestone itself also reports "Hooray! No issues to show here". Seems like something out of sync.

![obnux](https://cloud.githubusercontent.com/assets/12123/5818591/00ea54f0-a0b7-11e4-8306-fe83a6c84aba.png)

**Comment by derrickreimer** [comment]
Is there by chance an open pull request that was put under that milestone?

**Comment by lightcap** [comment]
It doesn't look like it, no.

**Comment by derrickreimer** [comment]
I just ran little query and it looks like there is one: https://codetree.com/projects/b1SW/issues?status=open&milestone=Grid

I'll classify this ticket as a usability issue.

**Comment by lightcap** [comment]
That shows up as no issues to me, how odd.

**Comment by derrickreimer** [comment]
Bah, sorry my fault...

https://codetree.com/projects/b1SW/issues?type=&status=open&milestone=Grid

**Comment by lightcap** [comment]
Ah, yes. That is accurate. Thanks! We generally keep a PR open for the
milestone until it's closed.
