### ISSUE TITLE
Redirect to dashboard when logged in

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#43]
When I'm already logged in and I visit codetree.com, I always just click on "View my dashboard". Please save me a click and redirect me to same place as that link instead of showing me this page.

**Comment by derrickreimer** [comment]
:+1:

**Comment by veganstraightedge** [comment]
🎉🚀🌈‼️

**Comment by derrickreimer** [comment]
Happy Friday :star2: :star2:
