### ISSUE TITLE
New workflow columns show up after "Done"

### ISSUE THREAD

**Issue by lightcap** [codetree/feedback#45]
Excited to see we can add columns to the task board! Thanks!

There seems to be a bug that has the column show up after my "Done" column though.

![8luzn](https://cloud.githubusercontent.com/assets/12123/5903482/403286b2-a582-11e4-8988-7259d195a2ac.png)

**Comment by lightcap** [comment]
Wow, disregard this. I just can't read :-) This is not an issue, the "Done" column was just off the screen.

**Comment by derrickreimer** [comment]
This is my favorite kind of bug! :)
