### ISSUE TITLE
Repo picker is overwhelming

### ISSUE THREAD

**Issue by aseemk** [codetree/feedback#5]
If you have 100 repos to pick from, the dropdown (in the settings UI, or list in the onboarding UI) is borderline unusable. The repos aren't sorted in any obvious order, and there's no search.

Consider sorting alphabetically (if possible), and adding a search-as-you-type box (e.g. chosen.js).

**Comment by derrickreimer** [comment]
Thanks for the tip on chosen.js -- looks like a very well-made plugin.

**Comment by simonwex** [comment]
:+1:

**Comment by lightcap** [comment]
:+1:
