### ISSUE TITLE
Card menus clipped by column boundaries

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#50]
![screenshot 2015-02-03 10 03 27](https://cloud.githubusercontent.com/assets/11926/6026053/32d2c058-ab8c-11e4-8d3c-d25b46ff951a.png)

**Comment by chrisocast** [comment]
+1 This is a serious issue for new projects/milestones where all columns are empty.

**Comment by derrickreimer** [comment]
Also filed by @shaneog
