### ISSUE TITLE
Issue title gets completely covered by labels

### ISSUE THREAD

**Issue by aseemk** [codetree/feedback#51]
We have an admittedly oddball issue that has a lot of labels on it. (It's an umbrella-type issue for a work item that cuts across several areas of our repo.) The title has gotten completely covered up:

![screenshot 2015-02-05 01 54 09](https://cloud.githubusercontent.com/assets/537838/6056085/e679a1fa-acd9-11e4-94a0-6d3370b72d95.png)

I can't even find any element to click to visit that issue! =P

**Comment by derrickreimer** [comment]
Lol point taken :)
