### ISSUE TITLE
View task board without assignee or milestone filter

### ISSUE THREAD

**Issue by dblandin** [codetree/feedback#52]
Is there a way to view all open issues in a task board layout without filtering by assignee or milestone?

**Comment by derrickreimer** [comment]
This one is quickly percolating to the top of my development queue. Will keep everyone posted here.

**Comment by dblandin** [comment]
Great. thanks!

**Comment by ajwaxman** [comment]
+1

**Comment by derrickreimer** [comment]
At last, the global task board layout has shipped! You can now toggle any view between list and task board. The one kicker is that sorting within columns is only available when the task board is filtered down by a specific assignee or milestone (depending on the prioritization method you chose for your project). Big announcement coming in the next few days for this feature.

**Comment by ajwaxman** [comment]
:clap: :clap:
