### ISSUE TITLE
New labels added to issue on GitHub take awhile to show up in Codetree

### ISSUE THREAD

**Issue by lightyrs** [codetree/feedback#53]
Is this a limitation of the GitHub Issues API?

**Comment by derrickreimer** [comment]
Interesting, this should be fairly instantaneous. Was the delay in the magnitude of minutes or hours?

**Comment by lightyrs** [comment]
Our PM was doing a test of labels and was adding/removing a lot quickly so maybe that's what caused it but no labels showed up in Codetree:

![screen shot 2015-02-11 at 1 02 57 pm](https://cloud.githubusercontent.com/assets/334749/6152874/74b32982-b1ee-11e4-8fa3-bc9b5f89a8b1.png)

**Comment by derrickreimer** [comment]
Hm. Can you visit the Settings page on GitHub for that repository, click Webhooks & Services, and let me know if you see a codetree.com hook there?

**Comment by lightyrs** [comment]
I don't have access to that but I will ask someone else when they are around.  Thanks for your help.

**Comment by lightyrs** [comment]
It seems to be working now — sorry for the false alarm.

**Comment by derrickreimer** [comment]
No problem, let me know if you notice long delays again.
