### ISSUE TITLE
Newly created issues are not appearing on task boards immediately

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#55]
Behind the "New Issue" modal, basically. It's inconvenient to have to hit refresh to see the issue I just filed; especially when I forgot to prioritize it during creation and want to be able to grab it and move it to the top.

**Comment by derrickreimer** [comment]
Actually, this should be happening already. I have seen some cases happen though where the background refresh fails because of a race condition. Does it seem to never update for you?

**Comment by wanderingmatt** [comment]
It never updates for me. I typically create new issues from the task board view, if that helps you isolate things.

**Comment by derrickreimer** [comment]
Thanks Matt. Will look into this.
