### ISSUE TITLE
Ability to filter issues with an AND operator instead of only an OR operator

### ISSUE THREAD

**Issue by ajwaxman** [codetree/feedback#56]
I'm currently trying to create a shortcut for the intersection of two 2 labels

When I filter these two labels in GH's interface it gives me the intersection of issues: 

![](http://cl.ly/Zqqc/Image%202015-02-18%20at%204.22.56%20PM.png)

When I filter on Codetree it gives me the union of issues: 
![](http://cl.ly/Zpmo/Image%202015-02-18%20at%204.24.02%20PM.png)

Was there a reason you decided to go with the union instead of intersection when selecting multiple labels? This issue is as much as a question as a feature request. Other apps built on top of GH issues do what Codetree is doing so I'm sure there is a good reason that I'm not thinking of

**Comment by derrickreimer** [comment]
To be honest, I don't have a great rationale for choosing union over intersection :). I think there's value in both depending on how you are using labels. I'm definitely open to adding a toggle to switch between conjunction and disjunction when filtering.

**Comment by ajwaxman** [comment]
Sounds great! Definitely agree that there is value in both depending on how you use labels

**Comment by ezra-g** [comment]
Big +1 on this. We have 3-4 teams sharing a repo and being able to combine `status: in sprint` with `team: 1` labels would be hugely valuable to us.

**Comment by ezra-g** [comment]
To elaborate: While it's currently possible to filter by username for people within a particular sprint team, this still leaves the "unassigned" list of issues with issues that, under our label scheme, are irrelevant to the team. If we could combine our team and status labels, I believe we'd be able to start adopting Codetree for this particular group of teams.

**Comment by ezra-g** [comment]
@djreimer, is there any rough approximate potential timeframe for this feature?

**Comment by derrickreimer** [comment]
I'll expedite this for you @ezra-g. Aiming to ship by the end of the week.

**Comment by ezra-g** [comment]
Wowza - Thanks, @djreimer!

**Comment by derrickreimer** [comment]
:+1: I know you guys need this one badly, and you've been great customers :).

**Comment by ajwaxman** [comment]
Thanks so much @djreimer! :heart:

**Comment by derrickreimer** [comment]
Alrighty, this is now live. There's still some polishing to be done, but it should be working.

![codetree_-_board_ _codetree](https://cloud.githubusercontent.com/assets/341387/10700482/d5c00fdc-7972-11e5-8b85-ebc69f3f2573.png)

Just toggle the "All" option and it will return the conjunction.

**Comment by ezra-g** [comment]
Thanks so much, @djreimer! We'll try it out :).

**Comment by derrickreimer** [comment]
:+1: let me know how it works for you!

**Comment by ezra-g** [comment]
Will do!
