### ISSUE TITLE
All links should have a path/URL in its href 

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#57]
From a project's list of issues, if I try to command click or right click a label to open it in a new tab, it doesn't work. It fails to fire off into a new tab because the `href` is `javascript:;` which is neither a URL nor a glob of Javascript. 

With a combination of push/pop state and JS routing, you could keep this same behavior but still have real URLs in your `href`s. 

Alternately, you could just do normal page loads for links instead of ajax links.

`¯\_(ツ)_/¯`

**Comment by derrickreimer** [comment]
Fair point, sir!

**Comment by veganstraightedge** [comment]
Boom! 👍
