### ISSUE TITLE
Show repository names in task board view

### ISSUE THREAD

**Issue by rinopo** [codetree/feedback#58]
As a corollary of #40 I really wish I could see repository names of the issues in task board view, too.

Thanks for your consideration!

**Comment by derrickreimer** [comment]
:+1:

**Comment by derrickreimer** [comment]
Alrighty, this is live!

![repo-on-card](https://cloud.githubusercontent.com/assets/341387/6544013/8c330e16-c4ee-11e4-9837-0042503ed6d7.png)

**Comment by rinopo** [comment]
Wow, so fast!
Thanks a lot :blush:
