### ISSUE TITLE
Add a "Feedback" link 

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#59]
For easier access from Codetree to this Issues repo, maybe you could add a `Feedback` link somewhere on the Codetree site from there to here?

**Comment by derrickreimer** [comment]
:+1: this is the most "meta" issue yet :)

**Comment by derrickreimer** [comment]
![feedback-link](https://cloud.githubusercontent.com/assets/341387/6456598/566de7aa-c11b-11e4-9897-9fa056cc77d1.png)

**Comment by veganstraightedge** [comment]
Thanks!
