### ISSUE TITLE
Logomark feedback

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#60]
I'm not sure where to leave this feedback.

Your logo mark is very close to being a checkmark which pairs nicely with Issues/project management/todo tasks. If you (or you designer) did it right you could invoke a nice subtle checkmark (in the whitespace down the middle of the leaves) without loosing your pretty leaves or looking like every other checkmark app icon.
- Personally, I'd reduce the size of the smaller / left leaf relative to the bigger / right leaf, so that the ratio of downward stroke to upward stroke feels about like checkmark ratio.
- Then I'd play with giving either both leaves or just the right leaf a little bend so that their tops are curling away from their bases. That would make your negative space checkmark have a little curve to it too. (Either on both sides or just the right side.) _Definitely don't bend just the left leaf though. That'd make a weird checkmark._
- Finally, I'd play with line weight of the leaf spine to create a more organic feeling checkmark. As if it were drawn by a human hand using a sharpie marker. Or something like that.

---

Do whatever or nothing with this feedback. It's your site and brand. It was just a thought that popped into my brain just now.

**Comment by derrickreimer** [comment]
Thanks!
