### ISSUE TITLE
Allow filtering of issues by the absense of a label

### ISSUE THREAD

**Issue by dblandin** [codetree/feedback#61]
It would be great to be able to filter down to (and create a custom shortcut for) issues without a certain label.

We've been using GitHub Issues to plan features which aren't yet ripe for the dev team. We usually add a label of **planning** to these issues. This would be also useful for organization that label issues with **icebox**.

I usually filter out the issues that still require business planning with:

```
is:issue is:open -label:planning
```

Thoughts?

**Comment by derrickreimer** [comment]
Yep, this would definitely come in handy. You can actually accomplish this now by adding `exclude_labels=planning` to the query string (and creating a shortcut will retain it). This deserves a place in the UI.

**Comment by dblandin** [comment]
@djreimer Fantastic! So many tricks up your sleeve :)

**Comment by derrickreimer** [comment]
@dblandin added to the UI

**Comment by dblandin** [comment]
@djreimer Awesome! :+1:

**Comment by imwra** [comment]
Hey @djreimer seems like this isn't working if the label is also being used to define a stage...is this just me or is it an issue?

**Comment by derrickreimer** [comment]
Yes, I believe this is expected. The `exclude_labels` filter gets superseded in the board view for stage labels. It should work fine in the list view, though. Is there a use case for excluding issues in for an entire column in the board view? /cc @kareem
