### ISSUE TITLE
Add "exclude blockers" filter

### ISSUE THREAD

**Issue by chadbay** [codetree/feedback#62]
Here's what the issues look like, with issue 1 being blocked by 2 and 3:

```
issue 1: Build me a project management app
    needs 2 
    needs 3
issue 2: Wire up back-end
issue 3: write some JavaScript
issue 4: another parent issue, evaluate cloud providers
issue 5: five is someone's lucky number
```

Codetree's filter with blocked would show:

```
issue 1
```

I want to see:

```
issue 1
issue 4
issue 5
```

**Comment by derrickreimer** [comment]
:+1: that seems useful

**Comment by derrickreimer** [comment]
Alright sir! Just shipped the "Blocking" filter:

![not-blocking](https://cloud.githubusercontent.com/assets/341387/6544120/1ebea476-c4f3-11e4-8a72-5272772970d1.png)
