### ISSUE TITLE
Newly created labels aren't showing up in Codetree

### ISSUE THREAD

**Issue by dhicking** [codetree/feedback#63]
I've created a new label but it's not showing up in Codetree yet.  I tried manually syncing my data and I've also tried logging in and logging out.  Is this a bug?

**Comment by derrickreimer** [comment]
Hi Dave! Unfortunately GitHub doesn't send us a webhook when a label is created for the first time on a repository. However, Codetree will become aware of it as soon as it is used for the first time.

**Comment by dhicking** [comment]
Thanks for the heads up, that’s good to know.

**Comment by derrickreimer** [comment]
No problem!
