### ISSUE TITLE
Unable to drag an issue from Todo to Backlog via task board

### ISSUE THREAD

**Issue by wanderingmatt** [codetree/feedback#64]
I assumed this would be possible — stripping the issue of its current milestone — and tried to do it.

**Comment by derrickreimer** [comment]
That's strange, it should work like you expected. I will investigate.

**Comment by derrickreimer** [comment]
@WanderingMatt sorry about that, there was a little bug introduced yesterday. Should be fixed now, but please let me know if you run into it again!

**Comment by wanderingmatt** [comment]
Working. :+1:
