### ISSUE TITLE
Edited content doesn't update in codetree display

### ISSUE THREAD

**Issue by adro718** [codetree/feedback#65]
If I update a comment or title in github for an existing issue displaying in codetree, the updates do not display in codetree. Once I create a new comment for that issue the edits do update. It seems like codetree is only updating for new content not edited content.

**Comment by derrickreimer** [comment]
Hi Alex! Unfortunately, GitHub does not send us webhooks for title/body/comments are edited, or when the issue milestone is changed. I'm currently lobbying them to change that, but for now we have to rely on polling the API to bring those changes over to Codetree. Sorry for the inconvenience! We are actively looking for ways to make this better all the time.

**Comment by adro718** [comment]
Thanks for the update!
