### ISSUE TITLE
Label management

### ISSUE THREAD

**Issue by SeanBannister** [codetree/feedback#68]
Because codetree polls github for new labels and doesn't provide an interface to create new labels there's no way to apply a label to an issue when you first create it, you have to wait for codetree to poll.

**Comment by derrickreimer** [comment]
Thanks @SeanBannister -- updated the title to reflect the feature request.

**Comment by jasny** [comment]
:+1:

**Comment by derrickreimer** [comment]
Also requested by @slickrick1983 @rinopo

**Comment by derrickreimer** [comment]
From @slickrick1983:

> Currently codetree doesnt allow you to add the same labels accross repo's.
> I would like a screen similar to the milestone screen were I can manage the labels accross repo's

**Comment by derrickreimer** [comment]
First pass at this is live in all projects :star:

**Comment by rinopo** [comment]
Wow, so nice!

**Comment by derrickreimer** [comment]
Thanks!

**Comment by rinopo** [comment]
Would it be possible also to delete a label  from within Codetree from all the repos in a project?

**Comment by derrickreimer** [comment]
@rinopo yes, tracking this here #91

**Comment by derrickreimer** [comment]
Label deletion is now live
