### ISSUE TITLE
Cannot delete an organisation or a repository

### ISSUE THREAD

**Issue by SeanBannister** [codetree/feedback#69]
Once an organisation or repository is created there's no way to delete it.

**Comment by derrickreimer** [comment]
Hi @SeanBannister, we can definitely take care of that for you. Which organization would you like deleted?

**Comment by SeanBannister** [comment]
Thanks I'd actually like a project deleted, called "Test" under the Creative.Parts organisation.

**Comment by derrickreimer** [comment]
Got it -- so we do have delete project functionality in the UI. Click the "Issues" menu in the left hand side bar and then click "Settings". You should see a delete button there:

![delete-project](https://cloud.githubusercontent.com/assets/341387/7030431/5c4f92c6-dd19-11e4-98d0-fb74073b9075.png)

**Comment by ulgens** [comment]
If you didn't pay for the subscription, when you try to access project page, it redirects you to billing page. Because of this, accesing to issues page and deleting project is impossible.
