### ISSUE TITLE
Don't show creator (by default, at least)

### ISSUE THREAD

**Issue by aseemk** [codetree/feedback#7]
Always seeing two avatars (one assignee, one creator) adds some serious cognitive processing cost. =)

At least to me, assignee is always relevant, creator rarely so.

I really wish there were a way for me to hide the creator — it's really tripping me up! =P

**Comment by aseemk** [comment]
Minor related feedback (doesn't feel significant enough to create an issue about, but let me know if you'd like me to, whether for this one or in general going forward): instead of the "nobody" name w/ gray avatar, just leave the space blank, or maybe a simple "-" dash. Again, less cognitive overhead to differentiate; easier to see unassigned issues at a glance.

**Comment by 0b10011** [comment]
:+1:

**Comment by derrickreimer** [comment]
> instead of the "nobody" name w/ gray avatar, just leave the space blank, or maybe a simple "-" dash. Again, less cognitive overhead to differentiate; easier to see unassigned issues at a glance.

Makes sense. These have been replaced with dashes. LMK how that works for you.

I'm still mulling over options for the creator column. I definitely see your point on that one.

**Comment by wanderingmatt** [comment]
:+1:

**Comment by derrickreimer** [comment]
See https://secure.helpscout.net/conversation/66417658/89/

**Comment by derrickreimer** [comment]
Alright folks, I've completely hidden the "Creator" column as a test.
