### ISSUE TITLE
After linking a new repository to an existing project another user can't see issues from the new repository

### ISSUE THREAD

**Issue by beaugunderson** [codetree/feedback#71]
And additionally, on their 'edit' page for the project the new repository does not show up in the list of linked repositories.

**Comment by derrickreimer** [comment]
Does this user have access to that particular repository on GitHub? We only allow users to view issues for which they have GitHub access. If the user was recently granted permission, he or she may need to hit the "Sync my GitHub data" button to have Codetree re-sync permissions immediately.

Let me know if this does not work.

**Comment by beaugunderson** [comment]
Yes, when @madprime used the 'Sync my GitHub Data' function she was then able to see the newly-linked repository. :)

**Comment by derrickreimer** [comment]
Great :)
