### ISSUE TITLE
Manual sync operation for project milestones and labels

### ISSUE THREAD

**Issue by derrickreimer** [codetree/feedback#74]
/cc @beaugunderson

**Comment by beaugunderson** [comment]
cc @madprime :)

**Comment by beaugunderson** [comment]
Oh, I missed the 'Refresh' button on this page: https://codetree.com/projects/uFsu/milestones

That synced the milestone itself, but the main issues page doesn't show the issues have that milestone assigned yet.

And in the future we'll try to create our milestones from the milestones page and do the assigning there to avoid the sync lag; I didn't realize you could add them from that page. :)

**Comment by derrickreimer** [comment]
Ah yes, I forgot to mention that! Going to close this one for now.
