### ISSUE TITLE
Use webhook to listen to changes

### ISSUE THREAD

**Issue by jasny** [codetree/feedback#75]
When we update an issue on GitHub, the change doesn't appear in codetree. You need to manually refresh first. This gives rise to major miscommunication and the blood baths that follow.

If I look at the repository settings, I see that there are webhooks in place, but they don't seem to do anything.

**Comment by derrickreimer** [comment]
@jasny we actually listen for as many events as GitHub sends via webhooks. Unfortunately, GitHub does not send events when for some common updates:
- Update title
- Update body
- Update milestone assignment

(see https://developer.github.com/v3/activity/events/types/#issuesevent)

I'm currently lobbying them to send more, but for now we have to fallback to manual polling for these changes.
