### ISSUE TITLE
Incomplete search results

### ISSUE THREAD

**Issue by kellyrmilligan** [codetree/feedback#79]

**Comment by JohnLemberger** [comment]
The search problems appear to go deeper than the title on this issue.  For instance, we have multiple issues with "app" in both the title and descriptions, yet only one of them is returned when searching for "app".

**Comment by derrickreimer** [comment]
I will look into this!

**Comment by derrickreimer** [comment]
@kellyrmilligan @JohnLemberger are you guys still experiencing search inconsistencies? Reproducing this is proving difficult, I'm afraid. Will definitely keep digging though if the problem is persisting.

**Comment by kellyrmilligan** [comment]
still seeing this. looking at it again, I am filtered to a task board, a milestone, and assigned to me. I searched for a word in the title of the issue, and got no results, capitalized or not.

**Comment by derrickreimer** [comment]
Thanks -- I'll try that route to see if filters are interfering.

**Comment by JohnLemberger** [comment]
Here's another specific case:

Issue title: "edit profile item"    (no it isn't very descriptive, is it)
Issue description contains the word "edit" but neither "profile" nor "item"

Search for "edit" works.  Search for "item" works.

Search for "profile" returns no results.

**Comment by derrickreimer** [comment]
Ah that's interesting. So it appears our Elastic Search configuration might need to be adjusted. This is a good data point, thanks John.

**Comment by derrickreimer** [comment]
Examples
- Drip issue 902 is not showing up in search results
- Drip issue 448 for term "segment" or "segments", but is showing up for "bulk"

**Comment by derrickreimer** [comment]
It looks like this was a result of not enough search hits being fetched. I've increased the threshold to remedy this, but will continue adjusting/optimizing moving forward.
