### ISSUE TITLE
Issue milestone change not reflecting in app

### ISSUE THREAD

**Issue by dphaener** [codetree/feedback#8]
I moved one of my issues to a different, newly created milestone, and the change is not being propagated back to the app. New issues for that milestone have showed up, but not the one that was moved.

**Comment by dphaener** [comment]
Nevermind. It just took awhile for it to show up.

**Comment by derrickreimer** [comment]
Cool. Was going to ask -- did you make the change on GitHub or through the Codetree interface? If it was through GH, then (unfortunately) GH does not propagate a webhook back we have to wait for the next sync to occur, which currently runs hourly.

**Comment by dphaener** [comment]
I made the change in GH. I tried dragging the issue to the new milestone, but it didn't work. Possibly because the one issue I had there already hadn't been "anchored" to the top or bottom yet (the same issue I originally had when trying to sort issues)?

**Comment by derrickreimer** [comment]
Dragging between milestones is not there yet. There's some nuance there. But you can now click the milestone name to change it through CT.
