### ISSUE TITLE
Unable to sync delete Milestones

### ISSUE THREAD

**Issue by slickrick1983** [codetree/feedback#81]
I have delete all milestones through Github, as I wasn't able to delete it through CT ref #25, but it wont update. Deleted Milestones remain visible.

**Comment by derrickreimer** [comment]
Thanks Rick, I'll look into whats happening here. I think the best solution
will be for me to expedite issue #25 - it's too cumbersome to have to go to
each repo to delete the milestone when you have a lot of repos anyhow.
Thanks for your patience, I'll keep you in the loop.

On Wed, May 20, 2015 at 3:31 AM, slickrick1983 notifications@github.com
wrote:

> I have delete all milestones through Github, as I wasn't able to delete it
> through CT ref #25 https://github.com/codetree/feedback/issues/25, but
> it wont update. Deleted Milestones remain visible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codetree/feedback/issues/81.

## 

Derrick

**Comment by slickrick1983** [comment]
Tnx Derrick. Yea we have about 20 repo’s or so. So that’s a hussle. Same as label management L 

We need to change that though Github in each respective repo as well.

KRs Rick

Van: Derrick Reimer [mailto:notifications@github.com] 
Verzonden: woensdag 20 mei 2015 18:25
Aan: codetree/feedback
CC: slickrick1983
Onderwerp: Re: [feedback] Unable to sync delete Milestones (#81)

Thanks Rick, I'll look into whats happening here. I think the best solution
will be for me to expedite issue #25 - it's too cumbersome to have to go to
each repo to delete the milestone when you have a lot of repos anyhow.
Thanks for your patience, I'll keep you in the loop.

On Wed, May 20, 2015 at 3:31 AM, slickrick1983 notifications@github.com
wrote:

> I have delete all milestones through Github, as I wasn't able to delete it
> through CT ref #25 https://github.com/codetree/feedback/issues/25, but
> it wont update. Deleted Milestones remain visible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codetree/feedback/issues/81.

## 

Derrick

**Comment by derrickreimer** [comment]
Deleting milestones in CT has been deployed!
