### ISSUE TITLE
Assignee menu cutoff in stage with few issues

### ISSUE THREAD

**Issue by shaneog** [codetree/feedback#85]
When the number of issues in a column/swimlane/stage is low, the assignee dropdown menu gets cut off.

I'm using Firefox 40 (Dev channel) on OS X Yosemite.

![single-issue](https://cloud.githubusercontent.com/assets/130415/8013495/14a1777c-0ba0-11e5-92a2-985c607c134e.png)

**Comment by derrickreimer** [comment]
Thanks @shaneog - tracking this on #50.
