### ISSUE TITLE
Task board is not properly showing issues that have 2 labels related to custom stages

### ISSUE THREAD

**Issue by ajwaxman** [codetree/feedback#86]
I currently have a task board created that has [2 custom stages](http://cl.ly/bYNR). The first custom stage (`Sprint`), has the "Keep label when stage is changed" option turned on. When I drag an issue from the `Sprint` column to the `Checked Out` column, the issue disappears from the task board: 

![](http://g.recordit.co/Avs4vSBGAI.gif)

This bug looks similar to https://github.com/codetree/feedback/issues/80, but it was marked as a feature instead of a bug so I thought it'd be worth creating this issue as well. If it's duplicative feel free to close

**Comment by derrickreimer** [comment]
Thanks, this should not be happening. When you drag it to the Checked out column, is the `status: checked out` label applied to the issue?

**Comment by ajwaxman** [comment]
Yep! The `status: checked out` label is applied and the `status: in sprint` label is left alone (as expected). Seems to be an issue in how the UI is deciding which issues to show for that column

**Comment by derrickreimer** [comment]
Great, I'll get this fixed!

**Comment by ajwaxman** [comment]
Thanks!

**Comment by derrickreimer** [comment]
Alright, this one should be fixed now.

**Comment by ajwaxman** [comment]
Thanks! Working on our end :+1:
