### ISSUE TITLE
Add Milestone Deadline Support

### ISSUE THREAD

**Issue by mwbrooks** [codetree/feedback#88]
The most compelling feature of Codetree is the ability to group multiple repositories under one issue tracker interface. I absolutely love that I can mirror milestones across projects seamlessly. However, it becomes tedious to set each project milestone's deadline. It would be nice if this was an option under _Milestone Settings_.

![screen shot 2015-06-23 at 3 48 37 pm](https://cloud.githubusercontent.com/assets/21328/8319057/5dee4810-19bf-11e5-9d44-3089ea757849.png)

**Comment by derrickreimer** [comment]
:+1: Should be able to knock this out fairly quickly - will keep you in the loop!

**Comment by mwbrooks** [comment]
Awesome man, let me know if I can provide any other feedback!

**Comment by dphaener** [comment]
:+1: on this

**Comment by derrickreimer** [comment]
![image](https://cloud.githubusercontent.com/assets/341387/9023844/c2703ef2-3863-11e5-9bd8-a191bb2e2723.png)

**Comment by mwbrooks** [comment]
Hey @djreimer, sorry about the slow response and thanks a bunch for this update! I especially like the _Multiple Deadline_ message when there are conflicts.

I've signed up as a paying customer. Cheers man!

**Comment by derrickreimer** [comment]
:beers: cheers!
