### ISSUE TITLE
Add Milestone Description Support

### ISSUE THREAD

**Issue by mwbrooks** [codetree/feedback#89]
Similar to #88, a great addition would be the synchronization of the milestone description under the _Milestone Settings_ section.

![screen shot 2015-06-23 at 3 48 37 pm](https://cloud.githubusercontent.com/assets/21328/8319081/9c2359c2-19bf-11e5-93d0-99feeb9c00cc.png)

**Comment by derrickreimer** [comment]
:shipit: :fireworks:

**Comment by mwbrooks** [comment]
Awesome @djreimer, thanks!
