### ISSUE TITLE
Outstanding request tracking

### ISSUE THREAD

**Issue by derrickreimer** [codetree/feedback#9]
Requested by @simonwex.
- A report/filter to show issues that currently need the user's input, using a tagging convention (a la "fixes #xxx")
- More intelligent notifications?

**Comment by simonwex** [comment]
Another convention that already exists in Github is using mentions. Being able to ask, "Show me all the issues in which I haven't participated since I was mentioned"

**Comment by derrickreimer** [comment]
I like that!

**Comment by derrickreimer** [comment]
@simonwex check out the "unanswered" filter:

![unanswered-filter](https://cloud.githubusercontent.com/assets/341387/5179109/117d1d22-742d-11e4-8b61-56a8549f9ea8.png)

**Comment by davidascher** [comment]
:heart_eyes:

**Comment by simonwex** [comment]
<img src="http://media.giphy.com/media/14yp0WnXMeXq9y/giphy.gif">
