### ISSUE TITLE
New issue contents lost when waiting too long

### ISSUE THREAD

**Issue by edwinv** [codetree/feedback#95]
1. Start adding a "New Issue" in the CodeTree UI and fill in some fields
2. Wait until other events refresh the tickets in the background
3. The issue form will be emptied, resulting in a loss of data

We have diverted to Github for adding issues, but losing a description of a new issue is very frustrating.

**Comment by derrickreimer** [comment]
Wow, really sorry about that. :disappointed: This should not be happening. I will investigate.

**Comment by derrickreimer** [comment]
@edwinv just deployed something that should prevent this from happening. As you populate the new issue form, we now cache the form contents in local storage will rehydrate the form when the modal is brought back up, page refreshed, etc. This behavior is similar to the GitHub comment form, which auto-saves your draft.
