### ISSUE TITLE
Overflow in card causing horizontal scroll

### ISSUE THREAD

**Issue by edwinv** [codetree/feedback#96]
![codetree](https://cloud.githubusercontent.com/assets/563294/8746423/529b9558-2c89-11e5-8f95-b1dc6d0750b7.png)

When an issue has a long description without spaces, the content is the card is extended over its borders. This causes a horizontal scrollbar to appear in the list.

**Comment by derrickreimer** [comment]
Eww, I'll address this soon. Thanks @edwinv
