### ISSUE TITLE
CSS issue on task board view

### ISSUE THREAD

**Issue by dphaener** [codetree/feedback#97]
See attached, the dropdown for assigning the issue to someone has a display problem. Looks like it's not a simple z-index fix unfortunately. :)

<img width="310" alt="screen shot 2015-07-21 at 9 41 32 am" src="https://cloud.githubusercontent.com/assets/5187971/8806738/e8b3cea6-2f8c-11e5-94a3-61f37cb5dcea.png">

**Comment by derrickreimer** [comment]
Thanks - tracking this one here: #50
