### ISSUE TITLE
Fix "unanswered" filter for mixed-case usernames

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#99]
somebody said "Thanks @Dieterbe" on a ticket in github (in a repository that is included in the board)
yet it doesn't show up in the "unanswered by me" filter.

**Comment by Dieterbe** [comment]
same thing after i explicitly sync github.

**Comment by derrickreimer** [comment]
Mind sharing the repo name and issue number? You can email it to me if you'd prefer not to post it on a public forum. I can check to see if the interaction was somehow missed.

**Comment by Dieterbe** [comment]
the ticket has since been closed, but it was https://github.com/raintank/grafana/issues/299

actually i also just noticed there's a different 12 hour old, open ticket that i haven't gotten back to yet:
https://github.com/raintank/grafana/issues/295
it also doesn't show up :(

**Comment by derrickreimer** [comment]
Ah! I think it know what's happening. We downcase usernames when storing interactions, but the filter is performing a case-sensitive query on your username "Dieterbe". This is a bug - will push out a fix soon.

For now, this should do the trick: https://codetree.com/projects/mNzg/issues?type=&unanswered=dieterbe

**Comment by Dieterbe** [comment]
workaround works!

**Comment by Dieterbe** [comment]
also confirmed that a new highlight shows up instantly (i checked about 50s later), without needing to do a manual sync

**Comment by derrickreimer** [comment]
@Dieterbe This should be all fixed up now.
